services:
  - type: web
    name: proyecto-caso-banco
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: SUPABASE_DB_HOST
        sync: false
      - key: SUPABASE_DB_NAME
        sync: false
      - key: SUPABASE_DB_USER
        sync: false
      - key: SUPABASE_DB_PASSWORD
        sync: false
      - key: SUPABASE_DB_PORT
        sync: false
