# -*- coding: utf-8 -*-
"""KFold - Caso 2 - Gestión de datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PIa2DUYWRYaL9ce7kpbyGNFp56pGQaDd
"""

# Librerías
import pandas as pd
from sklearn import datasets
import numpy as np
from collections import Counter
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
from sklearn.pipeline import Pipeline
import numpy as np
import seaborn as sns
import scipy
import matplotlib.pyplot as plt
import sklearn.tree # Árboles de decisión
import sklearn.ensemble # Ensambles de modelos
import sklearn.model_selection
import sklearn.decomposition # Módulo donde encontramos el análisis de componentes principales
from sklearn import datasets
from collections import Counter
from statsmodels.stats.multicomp import pairwise_tukeyhsd

# Zona de Definición de funciones
def calcula_metricas(nombre_algoritmo,y_test,y_pred):
### CLASE POSITIVA (1) ###
    #Calculo la precisión del modelo
    from sklearn.metrics import precision_score
    precision = precision_score(y_test, y_pred)

    #Calculo la exactitud del modelo
    from sklearn.metrics import accuracy_score
    exactitud = accuracy_score(y_test, y_pred)

    #Calculo la sensibilidad del modelo
    from sklearn.metrics import recall_score
    sensibilidad = recall_score(y_test, y_pred)

    #Calculo el Puntaje F1 del modelo
    from sklearn.metrics import f1_score
    puntajef1 = f1_score(y_test, y_pred)

    #Calculo la curva ROC - AUC del modelo
    from sklearn.metrics import roc_auc_score
    roc_auc = roc_auc_score(y_test, y_pred)

### CLASE NEGATIVA (0) ###
    from sklearn.metrics import confusion_matrix
    labels = [1, 0]
    cm = confusion_matrix(y_test, y_pred, labels = labels)
    tp,fn,fp,tn = cm.ravel()

    #True Negative Rate / specificity
    TNR_recall_espec = round(tn/(tn+fp),6)

    #Negative Predictive Value
    NPV_precision = round(tn/(tn+fn),6)

    #Cálculo del F1 para la clase negativa
    F1_neg = round(2 * (NPV_precision * TNR_recall_espec) / (NPV_precision + TNR_recall_espec),2)

    ## Vector de Desempeño - Resumen de Métricas del Modelo
    df_1 = pd.DataFrame({'Modelo': [nombre_algoritmo],'Clase ':[1],'Exactitud': [exactitud],'Precisión': [precision],
                   'Sensibilidad': [sensibilidad], 'F1': [puntajef1],'AUC': [roc_auc]})
    df_2 = pd.DataFrame({'Modelo': '','Clase ':[0],'Exactitud': '','Precisión': [NPV_precision],
                   'Sensibilidad': [TNR_recall_espec], 'F1': [F1_neg],'AUC': ''})
   # df = df_1.append(df_2, ignore_index = True)
    df = pd.concat([df_1, df_2], ignore_index=True)

    return df

def matriz_confusion(y_test,y_pred):
    import matplotlib.pyplot as plt
    import seaborn as sns
    #Verifico la matriz de Confusión
    from sklearn.metrics import confusion_matrix
    matriz = confusion_matrix(y_test, y_pred,labels=[1, 0])

    ax = sns.heatmap(matriz, annot=True, cmap='Blues', fmt='g')
    ax.set_title('Matriz de Confusión\n\n');
    ax.set_xlabel('\nPredicción')
    ax.set_ylabel('Real ');

    ## Ticket labels - List must be in alphabetical order
    ax.xaxis.set_ticklabels(['True','False'])
    ax.yaxis.set_ticklabels(['True','False'])

    ## Display the visualization of the Confusion Matrix.
    plt.show()

# Se omite el proceso de Balanceo de clases
  # Control con Hiperparámetro

#Synthetic Minority Oversampling Technique_ + Submuestro de la clase mayoritaria + Balanceo parcial del dataset
def SMOTE_RUS (X_train,y_train,sample_smote,sample_rus,balancear=True):
    if balancear:
      import imblearn
      sm = imblearn.over_sampling.SMOTE(sampling_strategy=sample_smote,random_state=11)
      rus = imblearn.under_sampling.RandomUnderSampler(sampling_strategy=sample_rus,random_state=11)
      steps = [('SMOTE', sm), ('RUS', rus)] # Ponemos ambos pasos
      sm_rus = imblearn.pipeline.Pipeline(steps=steps) # Creamos un pipeline para realizar ambas tareas
      X_train_sm_rus, y_train_sm_rus = sm_rus.fit_resample(X_train, y_train)
      return X_train_sm_rus,y_train_sm_rus, sm_rus
    else: # Caso negativo:
      return X_train, y_train, None # Entregar None en ves del pipeline, datos se mantienen

#Dibuja los scores obtenidos como proceso de evaluación iterativo, recibe los resultados y el valor ideal
def plot_scores(scores, ideal):
    import matplotlib.pyplot as plt
    # creating the dataset
    dic_scores = dict(enumerate(scores.flatten(), 1))
    k = list(dic_scores.keys())
    valores = list(dic_scores.values())

    fig = plt.figure(figsize = (10, 5))

    # creating the xy plot
  #  plt.xlim( [ min(k), max(k) ] )          # Plot from x=0 to x=80.
  #  plt.ylim( [ min(scores), 1 ] )
   #Gráfico XY de los scores vs K-folds
    plt.text(max(k)/2,max(valores)+0.010,'Comportamiento del score', color='steelblue')
    plt.plot(k, valores, color ='steelblue')

    #Mustra línea de umbral establecida
    plt.text(max(k)/2,ideal-0.010,'Umbral de hipótesis',color='mediumblue')
    plt.plot(k,[ideal for _ in range(len(k))],color='mediumblue')

    #Muestra la línea promedio obtenida
    plt.text(max(k)/2,scores.mean()-0.010,'Score promedio',color='brown')
    plt.text(max(k)/2,scores.mean()-0.020, round(scores.mean(),6),color='brown')

    plt.plot(k,[scores.mean() for _ in range(len(k))],color='brown', linestyle='dashed')
    plt.xlabel("k-folds")
    plt.ylabel("score")
    plt.suptitle("Scores de algoritmo evaluado mediante k-fold estratificado")
    plt.title("score ideal del proyecto F1 = 0.8")
    plt.show()

# Carga de datos depurados
data = pd.read_csv("datos_02_bank_validados.csv")
df2 = data.groupby(['deposit'])['deposit'].count()
df2

# Separar las variables dependientes de la independientes
y = data['deposit'] # Solo etiquetados (var objetivos)
X = data.drop(['deposit','duration','fecha_procesamiento' ], axis = 1) # Quitar variable estado como predictora, limpiar var objetivo

#Captura los nombres de las variables independientes
cols = X.columns

#Cuenta la cantidad de registros por cada clase
Counter(y)

# Separación de datos
# Zona Train y Zona Test (20%)
from sklearn.model_selection import train_test_split

# Se separa el dataset en entrenamiento y prueba.
# IMPORTANTE:
# El conjunto de prueba queda reservado para la evaluación final del modelo.
# Por eso, la validación cruzada se realizará solamente sobre X_train_raw e y_train_raw.
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=0,
    stratify=y
)

# Se realiza el reemplazo de X_train_raw a X_train, de igual modo en test

# Escalamiento de datos
# (Transformar variables a escala común )
from sklearn.preprocessing import MinMaxScaler

# IMPORTANTE:
# El escalador se ajusta solamente con el conjunto de entrenamiento original.
# Así se evita fuga de datos desde el conjunto de prueba.
escalar = MinMaxScaler()

X_train = escalar.fit_transform(X_train)  # aprende mínimos y máximos solo desde entrenamiento
X_test = escalar.transform(X_test)        # aplica la misma escala al conjunto de prueba

# Cuenta la cantidad de registros por cada clase del conjunto de entrenamiento original
Counter(y_train)
# Datos originales por clase: Counter({1: 5289, 0: 5872})
# Actual: Counter({1: 4231, 0: 4697}) (Se refiere a los datos de entrenamiento?? Post división?)

# Zona de Balanceo de clases (Omitir)
#SMOTE(sampling_strategy=0.5, random_state=0)
#RandomUnderSampler(sampling_strategy=0.75, random_state=0)

# En este caso de estudio, no se requiere balanceo de clases
# Invocar función SMOTE + RUS solamente sobre el conjunto de entrenamiento escalado
# IMPORTANTE:
# El balanceo no se aplica sobre X_test, porque el conjunto de prueba debe representar datos no vistos.
#X_train, y_train, pipeline_balanceo = SMOTE_RUS(X_train, y_train_raw, 0.5, 0.75)

# Cuenta la cantidad de registros del set de entrenamiento post balanceo
#Counter(y_train)

# Evaluación con modelo 'Decision Tree Classifier'
from sklearn.tree import DecisionTreeClassifier
tree_clf = DecisionTreeClassifier(max_depth=8,criterion = 'entropy') # Entropía => Medición de impurezas

# Entrenar el modelo
tree_clf.fit(X_train, y_train)

# Realizo una predicción
y_pred = tree_clf.predict(X_test)

# Cálculo y despliegue de la Matriz de confusión
matriz_confusion(y_test,y_pred)

# Total = 848(VP) + 210(FN) + 178(FP) + 997(VN) = 2233
# Resultado de evaluación del 20% de los datos (zona test) con Árbol de decisión

# Con una profundidad de 8, la exactitud es de un 80.03%
# acc = 848 + 997 / 2233 = 82.62 aprox

# Comparación K-Fold (Explicabilidad y replicabilidad)
# Librerías
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier

# # Motor de validación:
# random_state fijo (11) para garantizar que funcione
# Justifica que se obtengan los mismos resultados al correr ls pruebas
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=11)

# Inicializar algoritmos
modelos_clasificacion = {
    'Regresión Logística': LogisticRegression(max_iter=1000, random_state=0),
    'Árbol de Decisión': DecisionTreeClassifier(max_depth=8, criterion='entropy', random_state=0),
    'Perceptrón Multicapa': MLPClassifier(hidden_layer_sizes=(50, 25), max_iter=500, random_state=0)
}

# Diccionario dinámico para almacenar los F1-Scores de cada pliegue (Entrenamiento)
f1_historico_kfold = {nombre: [] for nombre in modelos_clasificacion.keys()}

print("Ejecutando comparación de K-Fold sobre el 80% de datos (Entrenamiento)...")

# Iteración de K-folds
# Separamos el X_train e y_train en 5 porciones dinámicas.
for train_idx, val_idx in skf.split(X_train, y_train):
    # Particiones internas del fold actual
    X_tr_fold, X_val_fold = X_train[train_idx], X_train[val_idx]

    # Manejo seguro de indexación
    y_tr_fold = y_train.iloc[train_idx] if hasattr(y_train, 'iloc') else y_train[train_idx]
    y_val_fold = y_train.iloc[val_idx] if hasattr(y_train, 'iloc') else y_train[val_idx]

    for nombre, modelo in modelos_clasificacion.items():
      # Entrenar modelo en proporción del pliegue actual
        modelo.fit(X_tr_fold, y_tr_fold)
        # Evaluar el rendimiento en la porción de validación
        y_pred_fold = modelo.predict(X_val_fold)
        # Guardar F1-Score real calculado para la clase positiva (1)
        score_fold = f1_score(y_val_fold, y_pred_fold, pos_label=1)
        f1_historico_kfold[nombre].append(score_fold)

print("K-Fold completado")

# Re-entrenamiento total y Evaluación en Test
print("Entrenando modelos finales y evaluando 20% (Test)...")
f1_test_resultados = {}

for nombre, modelo in modelos_torneo.items():
    # entrenar modelo con totalidad combinada (8,928 registros)
    modelo.fit(X_train, y_train)
    # Forzar a predecir sobre el conjunto de test que jamás ha visto (2,233 registros)
    y_pred_test = modelo.predict(X_test)
    # Calcular el F1-Score real
    f1_test_resultados[nombre] = f1_score(y_test, y_pred_test, pos_label=1)

print("Evaluación de Prueba completada")

# Gráfico
# Media matemática real de los 5 pliegues y su desviación estándar
f1_kfold_promedios = {nombre: np.mean(scores) for nombre, scores in f1_historico_kfold.items()}
f1_kfold_desviaciones = {nombre: np.std(scores) for nombre, scores in f1_historico_kfold.items()}

# Dashboard
algoritmos = list(modelos_clasificacion.keys())
x = np.arange(len(algoritmos))
width = 0.35

fig, ax = plt.subplots(figsize=(11, 6))

# Dibujamos las barras de Entrenamiento basadas estrictamente en la media matemática calculada arriba
rects1 = ax.bar(x - width/2, f1_kfold_promedios.values(), width,
                yerr=f1_kfold_desviaciones.values(), capsize=7,
                label='Entrenamiento (Media K-Fold Calculada)', color='green', edgecolor='green')

# Dibujamos las barras de Prueba basadas estrictamente en la predicción
rects2 = ax.bar(x + width/2, f1_test_resultados.values(), width,
                label='Prueba Final (Conjunto Test Real)', color='purple', edgecolor='purple')

# Línea del umbral objetivo del negocio (F1 = 0.8)
ax.axhline(y=0.8, color='black', linestyle='--', linewidth=2, label='Umbral de Éxito Objetivo (F1 = 0.8)')

# Ajustes estéticos y de presentación
ax.set_ylabel('F1-Score (Clase 1 - "Deposit")', fontsize=12, fontweight='bold')
ax.set_title('Estabilidad de Entrenamiento (K-Fold) vs Generalización en Prueba (Test))', fontsize=14, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(algoritmos, fontsize=11, fontweight='bold')
ax.set_ylim(0, 1.0)
ax.grid(axis='y', linestyle=':', alpha=0.6)
ax.legend(loc='lower right', fontsize=11)

# Ajustar valores sobre barras
def autolabel(rects):
    for rect in rects:
        height = rect.get_height()
        ax.annotate(f'{height:.4f}',
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 3),
                    textcoords="offset points",
                    ha='center', va='bottom', fontsize=10, fontweight='bold')

autolabel(rects1)
autolabel(rects2)

plt.tight_layout()
plt

# Exportación de modelo y escalado
import joblib
from google.colab import files

# Modelo: Entrenamiento
# Escalado: Filtro dew traducción

# Extraer modelo entrenado
modelo_seleccionado = modelos_clasificacion['Perceptrón Multicapa']

# Guardar modelo en entorno local
nombre_modelo_pkl = 'modelo_perceptron_multicapa.pkl'
joblib.dump(modelo_seleccionado, nombre_modelo_pkl)
print(f" Modelo guardado como: {nombre_modelo_pkl}")

# Guardar el escalador ('escalar')
nombre_scaler_pkl = 'escalador_minmax.pkl'
joblib.dump(escalar, nombre_scaler_pkl)
print(f" Escalador guardado como: {nombre_scaler_pkl}")

print("\n Iniciando descarga automática...")

print("\n Archivos listos!")

# Forzar la descarga de ambos archivos
files.download(nombre_modelo_pkl)
files.download(nombre_scaler_pkl)