# -*- coding: utf-8 -*-
"""Pruebas de Seguridad - Caso2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MSYzxfVzYYH30gfNWIkAv5Wovk6hCP4g
"""

# Datos de Identificación del análisis
# =========================
# IDENTIFICACIÓN DEL ANÁLISIS
# =========================

NOMBRE_ESTUDIANTE = "Catalina Kupfer"
SECCION = "ITY1101-001D"
NOMBRE_PROYECTO = "Proyecto: Pipeline DataOps para caso de estudio Bank Marketing"

# Repositorio a evaluar.
# Por defecto se deja el repositorio docente de ejemplo trabajado en clases.
REPO_URL = "https://github.com/kuaruan/proyecto-caso-banco"

# Carpeta local donde se clonará o actualizará el repositorio.
LOCAL_REPO_DIR = "proyecto-caso-banco"# C:\Users\kuuup\proyecto-caso-banco

# Rama opcional. Dejar None para usar la rama por defecto del repositorio.
BRANCH = None

# Carpeta donde se guardarán los resultados.
SALIDA_DIR = "outputs_seguridad"

# Activar herramientas externas solo si están instaladas localmente.
# El notebook funciona aunque no estén instaladas; en ese caso deja la observación correspondiente.
EJECUTAR_HERRAMIENTAS_EXTERNAS = True

# Revisión del host local. Por seguridad se deja apagada.
# Al activarla, revisa únicamente puertos del propio computador/entorno local, no redes externas.
EJECUTAR_REVISION_LOCALHOST = False

# Puertos que suelen ser delicados si quedan expuestos sin control.
PUERTOS_SENSIBLES = {"5432", "3306", "27017", "6379", "9200", "9300", "1433", "1521", "5984"}

# Extensiones de texto a revisar para secretos/configuración.
EXTENSIONES_TEXTO = {
    ".py", ".ipynb", ".js", ".ts", ".json", ".yaml", ".yml", ".toml", ".ini", ".cfg",
    ".env", ".txt", ".md", ".sql", ".sh", ".bat", ".ps1", ".properties", ".conf"
}

# Carpetas que se omiten para evitar falsos positivos y acelerar la revisión.
CARPETAS_OMITIDAS = {
    ".git", ".venv", "venv", "env", "__pycache__", ".ipynb_checkpoints", "node_modules",
    "dist", "build", ".mypy_cache", ".pytest_cache", ".ruff_cache", ".cache"
}

# Preparación de librerías y funciones base
from __future__ import annotations

import os
import re
import json
import time
import shutil
import hashlib
import platform
import subprocess
from pathlib import Path
from datetime import datetime
from urllib.parse import urlparse

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

try:
    import yaml
except ImportError:
    yaml = None

pd.set_option("display.max_colwidth", 160)
pd.set_option("display.max_rows", 200)

SALIDA_DIR = Path(SALIDA_DIR)
LOCAL_REPO_DIR = Path(LOCAL_REPO_DIR)
SALIDA_DIR.mkdir(parents=True, exist_ok=True)

FECHA_ANALISIS = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

SEVERIDAD_ORDEN = {
    "Crítico": 5,
    "Alto": 4,
    "Medio": 3,
    "Bajo": 2,
    "Informativo": 1,
    "OK": 0,
}

CATEGORIAS = [
    "Credenciales y secretos",
    "Accesos y configuración",
    "Dependencias y vulnerabilidades",
    "Docker y entorno de ejecución",
    "CI/CD y GitHub",
    "Logs y monitoreo",
    "Documentación de seguridad",
]

hallazgos = []

def agregar_hallazgo(categoria, control, resultado, severidad, evidencia, recomendacion, accion_sugerida="", herramienta="Notebook"):
    """Agrega un hallazgo a la lista global de resultados."""
    hallazgos.append({
        "categoría": categoria,
        "control evaluado": control,
        "resultado": resultado,
        "severidad": severidad,
        "evidencia": evidencia,
        "recomendación": recomendacion,
        "acción sugerida": accion_sugerida,
        "herramienta": herramienta,
    })


def ejecutar_comando(cmd, cwd=None, timeout=120):
    """Ejecuta un comando local sin exponer errores fatales al notebook."""
    try:
        inicio = time.perf_counter()
        proc = subprocess.run(
            cmd,
            cwd=str(cwd) if cwd else None,
            capture_output=True,
            text=True,
            timeout=timeout,
            shell=False,
        )
        return {
            "cmd": " ".join(cmd),
            "returncode": proc.returncode,
            "stdout": proc.stdout,
            "stderr": proc.stderr,
            "tiempo_s": round(time.perf_counter() - inicio, 3),
            "ok": proc.returncode == 0,
        }
    except FileNotFoundError:
        return {
            "cmd": " ".join(cmd),
            "returncode": None,
            "stdout": "",
            "stderr": f"Comando no disponible: {cmd[0]}",
            "tiempo_s": 0,
            "ok": False,
        }
    except subprocess.TimeoutExpired:
        return {
            "cmd": " ".join(cmd),
            "returncode": None,
            "stdout": "",
            "stderr": f"Timeout ejecutando: {' '.join(cmd)}",
            "tiempo_s": timeout,
            "ok": False,
        }


def es_archivo_texto(path: Path) -> bool:
    if path.suffix.lower() in EXTENSIONES_TEXTO:
        return True
    try:
        with open(path, "rb") as f:
            chunk = f.read(2048)
        return b"\0" not in chunk
    except Exception:
        return False


def leer_texto_seguro(path: Path, max_bytes=2_000_000) -> str:
    """Lee texto limitando tamaño para evitar cargar archivos gigantes."""
    try:
        if path.stat().st_size > max_bytes:
            return ""
        return path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return ""


def archivos_revisables(repo_dir: Path):
    for path in repo_dir.rglob("*"):
        if not path.is_file():
            continue
        if any(part in CARPETAS_OMITIDAS for part in path.parts):
            continue
        if es_archivo_texto(path):
            yield path


def ruta_relativa(path: Path, repo_dir: Path) -> str:
    try:
        return str(path.relative_to(repo_dir)).replace("\\", "/")
    except ValueError:
        return str(path)


def redactar_valor(valor: str, visible_inicio=4, visible_fin=2) -> str:
    """Redacta valores potencialmente sensibles. No imprime secretos completos."""
    if valor is None:
        return ""
    valor = str(valor).strip()
    if len(valor) <= visible_inicio + visible_fin + 3:
        return "***"
    return valor[:visible_inicio] + "***" + valor[-visible_fin:]


def clasificar_severidad_texto(valor):
    return SEVERIDAD_ORDEN.get(valor, 0)

print("Entorno listo")
print("Fecha de análisis:", FECHA_ANALISIS)
print("Sistema operativo:", platform.platform())

# Clonación / Actualización del repositorio (Corregido)
def clonar_o_actualizar_repo(repo_url: str, destino: Path, branch=None):
    destino.parent.mkdir(parents=True, exist_ok=True)

    if (destino / ".git").exists():
        print(f"Repositorio ya existe en: {destino}")
        resultado = ejecutar_comando(["git", "pull"], cwd=destino, timeout=180)
        if not resultado["ok"]:
            print("No fue posible actualizar con git pull. Se continuará con la copia local existente.")
            print(resultado["stderr"][:500])
        return destino

    cmd = ["git", "clone"]
    if branch:
        cmd += ["--branch", branch]
    cmd += [repo_url, str(destino)]

    print("Clonando repositorio...")
    resultado = ejecutar_comando(cmd, timeout=300)
    if not resultado["ok"]:
        raise RuntimeError(
            "No fue posible clonar el repositorio. Revisa conexión, permisos o URL.\n"
            + resultado["stderr"][:1000]
        )
    return destino

repo_dir = clonar_o_actualizar_repo(REPO_URL, LOCAL_REPO_DIR, BRANCH)
print("Repositorio preparado en:", repo_dir.resolve())

# Perfil inicial del repositorio
def perfilar_repositorio(repo_dir: Path):
    archivos = []
    for p in repo_dir.rglob("*"):
        if p.is_file() and not any(part in CARPETAS_OMITIDAS for part in p.parts):
            rel = ruta_relativa(p, repo_dir)
            archivos.append({
                "archivo": rel,
                "extensión": p.suffix.lower() or "sin extensión",
                "tamaño_kb": round(p.stat().st_size / 1024, 2),
            })
    df = pd.DataFrame(archivos)
    return df

df_archivos = perfilar_repositorio(repo_dir)

df_resumen_ext = (
    df_archivos.groupby("extensión", as_index=False)
    .agg(cantidad=("archivo", "count"), tamaño_total_kb=("tamaño_kb", "sum"))
    .sort_values(["cantidad", "tamaño_total_kb"], ascending=False)
)

archivos_clave = [
    "Dockerfile", "docker-compose.yml", "compose.yml", "requirements.txt", "pyproject.toml",
    "package.json", "package-lock.json", ".env", ".env.example", ".gitignore",
    "README.md", "SECURITY.md", ".github/dependabot.yml"
]

df_archivos_clave = df_archivos[df_archivos["archivo"].apply(lambda x: Path(x).name in archivos_clave or x.startswith(".github/workflows/"))]

print(f"Total de archivos revisables/directorio: {len(df_archivos)}")
display(df_resumen_ext.head(20))
display(df_archivos_clave.sort_values("archivo"))

# Revisión de credenciales, claves y archivos sensibles
PATRONES_SECRETOS = [
    ("AWS Access Key", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("GitHub token", re.compile(r"\bgh[pousr]_[A-Za-z0-9_]{20,}\b")),
    ("Private key", re.compile(r"-----BEGIN (RSA |DSA |EC |OPENSSH |PGP )?PRIVATE KEY-----")),
    ("Connection string", re.compile(r"(?i)(mongodb(\+srv)?|postgresql|mysql|mssql|redis)://[^\s'\"]+")),
    ("Variable sensible", re.compile(
        r"(?i)\b(password|passwd|pwd|token|secret|api[_-]?key|access[_-]?key|private[_-]?key|client[_-]?secret|database_url|mongo_uri|postgres_password|jwt_secret)\b\s*[:=]\s*['\"]?([^'\"\n#\s]{6,})"
    )),
]

VALORES_PLACEHOLDER = re.compile(r"(?i)(example|ejemplo|demo|dummy|changeme|change_me|your_|xxxxx|xxxx|none|null|localhost|\$\{|os\.getenv|process\.env)")


def revisar_secretos(repo_dir: Path):
    encontrados = 0

    # Archivos .env reales versionados
    env_files = []
    for p in repo_dir.rglob(".env*"):
        if p.is_file() and not any(part in CARPETAS_OMITIDAS for part in p.parts):
            rel = ruta_relativa(p, repo_dir)
            if not any(token in p.name.lower() for token in ["example", "sample", "template", "plantilla"]):
                env_files.append(rel)

    if env_files:
        agregar_hallazgo(
            "Credenciales y secretos",
            "Archivos .env versionados",
            "Se detectaron archivos .env que podrían contener credenciales reales.",
            "Alto",
            ", ".join(env_files[:10]),
            "No versionar archivos .env reales. Mantener solo .env.example sin valores sensibles.",
            "Eliminar .env del repositorio, rotar credenciales si fueron expuestas y agregar .env a .gitignore.",
        )
    else:
        agregar_hallazgo(
            "Credenciales y secretos",
            "Archivos .env versionados",
            "No se detectaron archivos .env reales versionados.",
            "OK",
            "No hay .env reales detectados.",
            "Mantener esta práctica y versionar solo plantillas .env.example.",
        )

    # Revisión de .gitignore
    gitignore = repo_dir / ".gitignore"
    if gitignore.exists():
        contenido = leer_texto_seguro(gitignore).lower()
        if ".env" in contenido or "*.env" in contenido:
            agregar_hallazgo(
                "Credenciales y secretos",
                "Protección en .gitignore",
                ".gitignore contiene reglas para excluir archivos .env.",
                "OK",
                ".gitignore incluye patrón relacionado con .env.",
                "Mantener reglas de exclusión de secretos.",
            )
        else:
            agregar_hallazgo(
                "Credenciales y secretos",
                "Protección en .gitignore",
                ".gitignore existe, pero no se observó una regla clara para .env.",
                "Medio",
                ".gitignore sin patrón .env explícito.",
                "Agregar .env y variantes sensibles al .gitignore.",
                "Incluir .env, .env.*, !.env.example según corresponda.",
            )
    else:
        agregar_hallazgo(
            "Credenciales y secretos",
            "Protección en .gitignore",
            "No se encontró archivo .gitignore.",
            "Medio",
            "Archivo .gitignore ausente.",
            "Crear .gitignore para evitar subir credenciales, entornos virtuales y artefactos temporales.",
        )

    # Búsqueda de secretos hardcodeados
    for archivo in archivos_revisables(repo_dir):
        rel = ruta_relativa(archivo, repo_dir)
        texto = leer_texto_seguro(archivo)
        if not texto:
            continue
        for i, linea in enumerate(texto.splitlines(), start=1):
            if len(linea) > 1000:
                continue
            for nombre_patron, patron in PATRONES_SECRETOS:
                match = patron.search(linea)
                if not match:
                    continue

                valor_detectado = match.group(0)
                if nombre_patron == "Variable sensible" and len(match.groups()) >= 2:
                    valor_detectado = match.group(2)

                es_placeholder = bool(VALORES_PLACEHOLDER.search(valor_detectado))
                severidad = "Bajo" if es_placeholder else "Alto"
                resultado = "Posible secreto de ejemplo" if es_placeholder else "Posible secreto hardcodeado"
                evidencia = f"{rel}:{i} | {nombre_patron} | valor={redactar_valor(valor_detectado)}"
                recomendacion = "Usar variables de entorno o gestor de secretos. No dejar credenciales reales en código fuente."
                accion = "Verificar si el valor es real. Si es real, eliminarlo del historial y rotar la credencial."
                agregar_hallazgo("Credenciales y secretos", nombre_patron, resultado, severidad, evidencia, recomendacion, accion)
                encontrados += 1

    if encontrados == 0:
        agregar_hallazgo(
            "Credenciales y secretos",
            "Búsqueda de secretos hardcodeados",
            "No se detectaron patrones evidentes de secretos hardcodeados.",
            "OK",
            "Búsqueda por patrones básicos sin coincidencias de alto riesgo.",
            "Complementar con herramientas especializadas como GitHub Secret Scanning o Gitleaks si están disponibles.",
        )

revisar_secretos(repo_dir)
print("Revisión de secretos completada")

# Revisión de Docker, Docker Compose y Entorno de ejecución
def revisar_dockerfiles(repo_dir: Path):
    dockerfiles = [p for p in repo_dir.rglob("Dockerfile*") if p.is_file() and not any(part in CARPETAS_OMITIDAS for part in p.parts)]
    if not dockerfiles:
        agregar_hallazgo(
            "Docker y entorno de ejecución",
            "Dockerfile",
            "No se detectaron Dockerfiles.",
            "Informativo",
            "No aplica si el proyecto no usa contenedores.",
            "Si el pipeline se ejecuta en contenedores, versionar Dockerfile reproducible y seguro.",
        )
        return

    for dockerfile in dockerfiles:
        rel = ruta_relativa(dockerfile, repo_dir)
        texto = leer_texto_seguro(dockerfile)
        lineas = texto.splitlines()
        from_lines = [l.strip() for l in lineas if l.strip().upper().startswith("FROM ")]
        user_lines = [l.strip() for l in lineas if l.strip().upper().startswith("USER ")]
        healthcheck = any(l.strip().upper().startswith("HEALTHCHECK") for l in lineas)

        for l in from_lines:
            imagen = l.split()[1] if len(l.split()) > 1 else ""
            if ":latest" in imagen or ":" not in imagen:
                agregar_hallazgo(
                    "Docker y entorno de ejecución",
                    "Imagen base versionada",
                    "La imagen base no parece fijar una versión específica.",
                    "Medio",
                    f"{rel} | {l}",
                    "Evitar latest o imágenes sin versión para mejorar reproducibilidad y seguridad.",
                    "Usar etiquetas específicas o digest SHA de la imagen base.",
                )

        if not user_lines:
            agregar_hallazgo(
                "Docker y entorno de ejecución",
                "Usuario no root en contenedor",
                "No se detectó instrucción USER. El contenedor podría ejecutarse como root.",
                "Medio",
                rel,
                "Ejecutar procesos con usuario no privilegiado dentro del contenedor.",
                "Crear usuario de aplicación y agregar USER appuser al Dockerfile.",
            )
        elif any(re.search(r"(?i)^USER\s+root\b|^USER\s+0\b", l) for l in user_lines):
            agregar_hallazgo(
                "Docker y entorno de ejecución",
                "Usuario no root en contenedor",
                "El Dockerfile declara ejecución como root.",
                "Alto",
                f"{rel} | {'; '.join(user_lines)}",
                "Evitar ejecutar el proceso principal como root.",
                "Cambiar a usuario no privilegiado para reducir impacto ante una vulnerabilidad.",
            )

        for i, linea in enumerate(lineas, start=1):
            if re.match(r"(?i)^\s*ENV\s+", linea) and re.search(r"(?i)(password|token|secret|key|database_url|mongo_uri)", linea):
                agregar_hallazgo(
                    "Docker y entorno de ejecución",
                    "Secretos en Dockerfile",
                    "Se detectó posible variable sensible declarada con ENV.",
                    "Alto",
                    f"{rel}:{i} | {linea[:120]}",
                    "No declarar secretos en Dockerfile; usar secrets o variables inyectadas en tiempo de ejecución.",
                    "Mover valores sensibles a .env local, GitHub Secrets, Docker secrets o secret manager.",
                )
            if re.search(r"(?i)^\s*ADD\s+https?://", linea):
                agregar_hallazgo(
                    "Docker y entorno de ejecución",
                    "Descarga remota en Dockerfile",
                    "Se usa ADD desde URL remota.",
                    "Medio",
                    f"{rel}:{i} | {linea[:120]}",
                    "Evitar descargas remotas no verificadas durante build.",
                    "Usar COPY local o validar integridad con checksum.",
                )

        if not healthcheck:
            agregar_hallazgo(
                "Docker y entorno de ejecución",
                "Healthcheck de contenedor",
                "No se detectó HEALTHCHECK en Dockerfile.",
                "Bajo",
                rel,
                "Agregar HEALTHCHECK cuando el servicio sea de larga ejecución.",
                "Definir una verificación simple del endpoint o proceso principal.",
            )


def normalizar_puerto(puerto):
    texto = str(puerto)
    # formatos típicos: "5432:5432", "127.0.0.1:5432:5432", {target: 5432, published: 5432}
    if isinstance(puerto, dict):
        publicado = str(puerto.get("published", ""))
        target = str(puerto.get("target", ""))
        host_ip = str(puerto.get("host_ip", ""))
        return host_ip, publicado, target, texto
    partes = texto.split(":")
    if len(partes) == 1:
        return "", partes[0].split("/")[0], partes[0].split("/")[0], texto
    if len(partes) == 2:
        return "0.0.0.0", partes[0], partes[1].split("/")[0], texto
    return partes[0], partes[-2], partes[-1].split("/")[0], texto


def revisar_compose(repo_dir: Path):
    compose_files = []
    for patron in ["docker-compose*.yml", "docker-compose*.yaml", "compose*.yml", "compose*.yaml"]:
        compose_files.extend(repo_dir.rglob(patron))
    compose_files = [p for p in compose_files if p.is_file() and not any(part in CARPETAS_OMITIDAS for part in p.parts)]

    if not compose_files:
        agregar_hallazgo(
            "Docker y entorno de ejecución",
            "Docker Compose",
            "No se detectaron archivos Docker Compose.",
            "Informativo",
            "No aplica si el proyecto no usa Docker Compose.",
            "Si se usa Docker Compose, documentar servicios, redes, volúmenes y puertos necesarios.",
        )
        return

    if yaml is None:
        agregar_hallazgo(
            "Docker y entorno de ejecución",
            "Parser YAML",
            "PyYAML no está instalado, la revisión de Compose será limitada.",
            "Informativo",
            "Instalar pyyaml para revisar docker-compose.yml estructuralmente.",
            "Ejecutar: pip install pyyaml",
        )
        return

    for compose in compose_files:
        rel = ruta_relativa(compose, repo_dir)
        try:
            data = yaml.safe_load(leer_texto_seguro(compose)) or {}
        except Exception as e:
            agregar_hallazgo(
                "Docker y entorno de ejecución",
                "Lectura Docker Compose",
                "No fue posible parsear el archivo Compose.",
                "Medio",
                f"{rel} | error={e}",
                "Corregir sintaxis YAML para permitir revisión y despliegue confiable.",
            )
            continue

        services = data.get("services", {}) or {}
        if not services:
            agregar_hallazgo(
                "Docker y entorno de ejecución",
                "Servicios Docker Compose",
                "No se encontraron servicios declarados en Compose.",
                "Informativo",
                rel,
                "Verificar si el archivo es un fragmento o si el pipeline usa otra forma de ejecución.",
            )
            continue

        for servicio, conf in services.items():
            conf = conf or {}
            if conf.get("privileged") is True:
                agregar_hallazgo(
                    "Docker y entorno de ejecución",
                    "Contenedor privilegiado",
                    "Servicio ejecutado con privileged=true.",
                    "Alto",
                    f"{rel} | servicio={servicio}",
                    "Evitar contenedores privilegiados salvo justificación muy específica.",
                    "Eliminar privileged=true y conceder permisos mínimos necesarios.",
                )

            if conf.get("network_mode") == "host":
                agregar_hallazgo(
                    "Docker y entorno de ejecución",
                    "Network mode host",
                    "Servicio usa network_mode: host.",
                    "Alto",
                    f"{rel} | servicio={servicio}",
                    "Evitar exponer el contenedor directamente a la red del host.",
                    "Usar redes Docker internas y publicar solo puertos necesarios.",
                )

            for volumen in conf.get("volumes", []) or []:
                vol = str(volumen)
                if "/var/run/docker.sock" in vol:
                    agregar_hallazgo(
                        "Docker y entorno de ejecución",
                        "Montaje de docker.sock",
                        "El servicio monta /var/run/docker.sock.",
                        "Alto",
                        f"{rel} | servicio={servicio} | volumen={vol}",
                        "Montar docker.sock otorga control amplio sobre Docker del host.",
                        "Eliminar el montaje o reemplazar por mecanismo de permisos más restringido.",
                    )

            ports = conf.get("ports", []) or []
            for puerto in ports:
                host_ip, publicado, target, original = normalizar_puerto(puerto)
                if publicado in PUERTOS_SENSIBLES or target in PUERTOS_SENSIBLES:
                    severidad = "Alto" if host_ip in ["", "0.0.0.0"] else "Medio"
                    agregar_hallazgo(
                        "Accesos y configuración",
                        "Puerto sensible publicado",
                        "Se detectó publicación de puerto asociado a servicio sensible.",
                        severidad,
                        f"{rel} | servicio={servicio} | puerto={original}",
                        "Publicar puertos sensibles solo cuando sea estrictamente necesario y restringidos a localhost/VPN/firewall.",
                        "Usar 127.0.0.1:puerto:puerto para desarrollo local o redes internas de Docker.",
                    )
                elif ports:
                    agregar_hallazgo(
                        "Accesos y configuración",
                        "Puerto publicado",
                        "Se detectó puerto publicado para un servicio.",
                        "Bajo",
                        f"{rel} | servicio={servicio} | puerto={original}",
                        "Validar que el puerto sea necesario y esté protegido por autenticación o firewall.",
                    )

            envs = conf.get("environment", {}) or {}
            if isinstance(envs, list):
                env_items = envs
            else:
                env_items = [f"{k}={v}" for k, v in envs.items()]
            for item in env_items:
                if re.search(r"(?i)(password|token|secret|key|database_url|mongo_uri)", str(item)) and not re.search(r"\$\{|<|example|changeme", str(item), re.I):
                    agregar_hallazgo(
                        "Credenciales y secretos",
                        "Secretos en docker-compose",
                        "Posible valor sensible definido directamente en environment.",
                        "Alto",
                        f"{rel} | servicio={servicio} | {str(item).split('=')[0]}={redactar_valor(str(item).split('=',1)[-1])}",
                        "Evitar credenciales literales en docker-compose.yml.",
                        "Usar env_file local no versionado, Docker secrets o un gestor de secretos.",
                    )

            if "healthcheck" not in conf:
                agregar_hallazgo(
                    "Docker y entorno de ejecución",
                    "Healthcheck en Compose",
                    "Servicio sin healthcheck declarado.",
                    "Bajo",
                    f"{rel} | servicio={servicio}",
                    "Agregar healthcheck para detectar fallos de servicio y reinicios controlados.",
                )

revisar_dockerfiles(repo_dir)
revisar_compose(repo_dir)
print("Revisión Docker/Compose completada")

# Revisión de dependencias y vulnerabilidades conocidas
def revisar_dependencias(repo_dir: Path):
    requirements = list(repo_dir.rglob("requirements*.txt"))
    requirements = [p for p in requirements if p.is_file() and not any(part in CARPETAS_OMITIDAS for part in p.parts)]

    if requirements:
        for req in requirements:
            rel = ruta_relativa(req, repo_dir)
            lineas = [l.strip() for l in leer_texto_seguro(req).splitlines() if l.strip() and not l.strip().startswith("#")]
            no_pinned = [l for l in lineas if not re.search(r"(==|~=|>=|<=|>|<)", l)]
            if no_pinned:
                agregar_hallazgo(
                    "Dependencias y vulnerabilidades",
                    "Versionamiento de dependencias Python",
                    "Hay dependencias sin restricción de versión.",
                    "Medio",
                    f"{rel} | ejemplos={', '.join(no_pinned[:5])}",
                    "Fijar o restringir versiones para mejorar reproducibilidad y control de vulnerabilidades.",
                    "Usar requirements.txt versionado o herramientas como pip-tools/poetry/uv.",
                )
            else:
                agregar_hallazgo(
                    "Dependencias y vulnerabilidades",
                    "Versionamiento de dependencias Python",
                    "Las dependencias revisadas tienen restricciones de versión.",
                    "OK",
                    rel,
                    "Mantener actualización periódica y auditoría de vulnerabilidades.",
                )

            if EJECUTAR_HERRAMIENTAS_EXTERNAS:
                if shutil.which("pip-audit"):
                    res = ejecutar_comando(["pip-audit", "-r", str(req), "-f", "json"], cwd=repo_dir, timeout=180)
                else:
                    res = ejecutar_comando(["python", "-m", "pip_audit", "-r", str(req), "-f", "json"], cwd=repo_dir, timeout=180)

                if res["ok"] or res["stdout"].strip():
                    try:
                        data = json.loads(res["stdout"])
                        vulns = []
                        for dep in data.get("dependencies", []):
                            for vuln in dep.get("vulns", []) or []:
                                vulns.append({"paquete": dep.get("name"), "id": vuln.get("id"), "fix_versions": vuln.get("fix_versions")})
                        if vulns:
                            agregar_hallazgo(
                                "Dependencias y vulnerabilidades",
                                "pip-audit",
                                f"pip-audit detectó {len(vulns)} vulnerabilidades en dependencias Python.",
                                "Alto",
                                f"{rel} | primeras={vulns[:3]}",
                                "Actualizar dependencias vulnerables según versiones corregidas sugeridas.",
                                "Revisar reporte pip-audit completo y actualizar requirements.",
                                "pip-audit",
                            )
                        else:
                            agregar_hallazgo(
                                "Dependencias y vulnerabilidades",
                                "pip-audit",
                                "No se detectaron vulnerabilidades Python con pip-audit.",
                                "OK",
                                rel,
                                "Mantener auditorías periódicas en CI/CD.",
                                herramienta="pip-audit",
                            )
                    except Exception:
                        agregar_hallazgo(
                            "Dependencias y vulnerabilidades",
                            "pip-audit",
                            "No fue posible interpretar la salida de pip-audit.",
                            "Informativo",
                            f"{rel} | stderr={res['stderr'][:300]}",
                            "Verificar instalación de pip-audit y formato del archivo requirements.",
                            herramienta="pip-audit",
                        )
                else:
                    agregar_hallazgo(
                        "Dependencias y vulnerabilidades",
                        "pip-audit",
                        "pip-audit no está disponible o no pudo ejecutarse.",
                        "Informativo",
                        res["stderr"][:300],
                        "Instalar pip-audit para complementar la revisión de dependencias Python.",
                        "Ejecutar: pip install pip-audit",
                        "pip-audit",
                    )
    else:
        agregar_hallazgo(
            "Dependencias y vulnerabilidades",
            "requirements.txt",
            "No se encontraron archivos requirements.txt.",
            "Informativo",
            "No aplica si el proyecto no usa Python o usa otro gestor.",
            "Documentar claramente el gestor de dependencias utilizado.",
        )

    package_jsons = [p for p in repo_dir.rglob("package.json") if p.is_file() and not any(part in CARPETAS_OMITIDAS for part in p.parts)]
    for pkg in package_jsons:
        rel = ruta_relativa(pkg, repo_dir)
        lock = pkg.parent / "package-lock.json"
        if not lock.exists():
            agregar_hallazgo(
                "Dependencias y vulnerabilidades",
                "Lockfile Node.js",
                "Existe package.json pero no se encontró package-lock.json en la misma carpeta.",
                "Medio",
                rel,
                "Versionar lockfile para reproducibilidad y auditoría de dependencias.",
                "Ejecutar npm install para generar package-lock.json y versionarlo si corresponde.",
            )
        elif EJECUTAR_HERRAMIENTAS_EXTERNAS and shutil.which("npm"):
            res = ejecutar_comando(["npm", "audit", "--json"], cwd=pkg.parent, timeout=180)
            try:
                data = json.loads(res["stdout"] or "{}")
                total = data.get("metadata", {}).get("vulnerabilities", {}).get("total", 0)
                high = data.get("metadata", {}).get("vulnerabilities", {}).get("high", 0)
                critical = data.get("metadata", {}).get("vulnerabilities", {}).get("critical", 0)
                if total:
                    sev = "Crítico" if critical else "Alto" if high else "Medio"
                    agregar_hallazgo(
                        "Dependencias y vulnerabilidades",
                        "npm audit",
                        f"npm audit detectó {total} vulnerabilidades.",
                        sev,
                        f"{rel} | critical={critical}, high={high}",
                        "Actualizar dependencias Node.js vulnerables según npm audit.",
                        "Ejecutar npm audit fix con revisión y pruebas del pipeline.",
                        "npm audit",
                    )
                else:
                    agregar_hallazgo(
                        "Dependencias y vulnerabilidades",
                        "npm audit",
                        "No se detectaron vulnerabilidades Node.js con npm audit.",
                        "OK",
                        rel,
                        "Mantener auditoría automatizada en CI/CD.",
                        herramienta="npm audit",
                    )
            except Exception:
                agregar_hallazgo(
                    "Dependencias y vulnerabilidades",
                    "npm audit",
                    "No fue posible interpretar npm audit.",
                    "Informativo",
                    f"{rel} | stderr={res['stderr'][:300]}",
                    "Revisar instalación de npm y lockfile.",
                    herramienta="npm audit",
                )

    dependabot_paths = list(repo_dir.glob(".github/dependabot.yml")) + list(repo_dir.glob(".github/dependabot.yaml"))
    if dependabot_paths:
        agregar_hallazgo(
            "CI/CD y GitHub",
            "Dependabot",
            "Se detectó configuración de Dependabot.",
            "OK",
            ", ".join(ruta_relativa(p, repo_dir) for p in dependabot_paths),
            "Mantener revisión de PRs de actualización y pruebas automatizadas.",
        )
    else:
        agregar_hallazgo(
            "CI/CD y GitHub",
            "Dependabot",
            "No se detectó configuración de Dependabot.",
            "Medio",
            ".github/dependabot.yml ausente.",
            "Automatizar alertas/PRs de actualización de dependencias.",
            "Crear .github/dependabot.yml para pip, npm, Docker o GitHub Actions según corresponda.",
        )

    if EJECUTAR_HERRAMIENTAS_EXTERNAS and shutil.which("trivy"):
        res = ejecutar_comando(["trivy", "fs", "--format", "json", str(repo_dir)], timeout=300)
        if res["stdout"].strip():
            try:
                data = json.loads(res["stdout"])
                conteo = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "UNKNOWN": 0}
                for result in data.get("Results", []) or []:
                    for vuln in result.get("Vulnerabilities", []) or []:
                        sev = vuln.get("Severity", "UNKNOWN")
                        conteo[sev] = conteo.get(sev, 0) + 1
                total = sum(conteo.values())
                if total:
                    sev_global = "Crítico" if conteo.get("CRITICAL", 0) else "Alto" if conteo.get("HIGH", 0) else "Medio"
                    agregar_hallazgo(
                        "Dependencias y vulnerabilidades",
                        "Trivy filesystem scan",
                        f"Trivy detectó {total} vulnerabilidades.",
                        sev_global,
                        f"CRITICAL={conteo.get('CRITICAL',0)}, HIGH={conteo.get('HIGH',0)}, MEDIUM={conteo.get('MEDIUM',0)}",
                        "Revisar reporte Trivy y actualizar imágenes/dependencias vulnerables.",
                        "Priorizar CRITICAL y HIGH antes del despliegue.",
                        "trivy",
                    )
                else:
                    agregar_hallazgo(
                        "Dependencias y vulnerabilidades",
                        "Trivy filesystem scan",
                        "Trivy no detectó vulnerabilidades en el escaneo FS.",
                        "OK",
                        "Escaneo trivy fs sin vulnerabilidades reportadas.",
                        "Mantener escaneo en CI/CD.",
                        herramienta="trivy",
                    )
            except Exception:
                agregar_hallazgo(
                    "Dependencias y vulnerabilidades",
                    "Trivy filesystem scan",
                    "No fue posible interpretar la salida de Trivy.",
                    "Informativo",
                    res["stderr"][:300],
                    "Verificar versión de Trivy y ejecutar nuevamente.",
                    herramienta="trivy",
                )
    else:
        agregar_hallazgo(
            "Dependencias y vulnerabilidades",
            "Trivy",
            "Trivy no está disponible o no se solicitó ejecutar herramientas externas.",
            "Informativo",
            "Herramienta externa opcional no ejecutada.",
            "Instalar Trivy para analizar dependencias, imágenes y configuraciones de contenedores.",
            "Ejemplo local: trivy fs .",
            "trivy",
        )

revisar_dependencias(repo_dir)
print("Revisión de dependencias completada")

# Revisión de GitHub Actions, CI/CD y controles de repositorio
def revisar_github_actions(repo_dir: Path):
    workflows_dir = repo_dir / ".github" / "workflows"
    workflows = list(workflows_dir.glob("*.yml")) + list(workflows_dir.glob("*.yaml")) if workflows_dir.exists() else []

    if not workflows:
        agregar_hallazgo(
            "CI/CD y GitHub",
            "GitHub Actions",
            "No se detectaron workflows de GitHub Actions.",
            "Informativo",
            ".github/workflows ausente o sin YAML.",
            "Si el pipeline se ejecuta en CI/CD, versionar workflows con permisos mínimos.",
        )
    else:
        for wf in workflows:
            rel = ruta_relativa(wf, repo_dir)
            texto = leer_texto_seguro(wf)

            if not re.search(r"(?m)^permissions\s*:", texto):
                agregar_hallazgo(
                    "CI/CD y GitHub",
                    "Permisos mínimos en workflow",
                    "No se detectó bloque permissions explícito.",
                    "Medio",
                    rel,
                    "Definir permissions explícitos para reducir privilegios del GITHUB_TOKEN.",
                    "Agregar permissions: contents: read, y ampliar solo si es necesario.",
                )
            else:
                agregar_hallazgo(
                    "CI/CD y GitHub",
                    "Permisos mínimos en workflow",
                    "Workflow contiene bloque permissions explícito.",
                    "OK",
                    rel,
                    "Verificar que los permisos sean los mínimos necesarios.",
                )

            if re.search(r"(?m)^\s*pull_request_target\s*:", texto):
                agregar_hallazgo(
                    "CI/CD y GitHub",
                    "Evento pull_request_target",
                    "El workflow usa pull_request_target, evento que requiere controles estrictos.",
                    "Alto",
                    rel,
                    "Evitar ejecutar código no confiable con permisos elevados.",
                    "Usar pull_request cuando sea suficiente o restringir ejecución y revisión manual.",
                )

            if re.search(r"(?i)echo\s+.*\$\{\{\s*secrets\.", texto):
                agregar_hallazgo(
                    "CI/CD y GitHub",
                    "Exposición de secrets en logs",
                    "Se observó un posible echo de secrets en el workflow.",
                    "Alto",
                    rel,
                    "Nunca imprimir secretos en logs de CI/CD.",
                    "Eliminar echo de secrets y usar variables solo en comandos que las requieran.",
                )

            acciones = re.findall(r"uses:\s*([^\s#]+)", texto)
            acciones_inestables = [a for a in acciones if re.search(r"@(main|master|latest)$", a)]
            if acciones_inestables:
                agregar_hallazgo(
                    "CI/CD y GitHub",
                    "Versionamiento de actions",
                    "Se detectaron actions referenciadas a main/master/latest.",
                    "Medio",
                    f"{rel} | {', '.join(acciones_inestables[:5])}",
                    "Fijar versiones estables de acciones para evitar cambios inesperados.",
                    "Usar tags versionados o SHA cuando el contexto lo requiera.",
                )


def revisar_documentacion_seguridad(repo_dir: Path):
    security_md = repo_dir / "SECURITY.md"
    readme = repo_dir / "README.md"
    codeowners = repo_dir / ".github" / "CODEOWNERS"

    if security_md.exists():
        agregar_hallazgo(
            "Documentación de seguridad",
            "SECURITY.md",
            "Se detectó archivo SECURITY.md.",
            "OK",
            "SECURITY.md presente.",
            "Mantener instrucciones de reporte de vulnerabilidades y alcance de soporte.",
        )
    else:
        agregar_hallazgo(
            "Documentación de seguridad",
            "SECURITY.md",
            "No se detectó SECURITY.md.",
            "Bajo",
            "SECURITY.md ausente.",
            "Agregar política breve de seguridad para reportar vulnerabilidades y criterios de manejo.",
        )

    if codeowners.exists():
        agregar_hallazgo(
            "Documentación de seguridad",
            "CODEOWNERS",
            "Se detectó CODEOWNERS.",
            "OK",
            ".github/CODEOWNERS presente.",
            "Mantener revisión obligatoria para archivos críticos del pipeline.",
        )
    else:
        agregar_hallazgo(
            "Documentación de seguridad",
            "CODEOWNERS",
            "No se detectó CODEOWNERS.",
            "Bajo",
            ".github/CODEOWNERS ausente.",
            "Usar CODEOWNERS para exigir revisión de cambios en workflows, Docker, scripts y configuración.",
        )

    if readme.exists():
        texto = leer_texto_seguro(readme).lower()
        menciones = [t for t in ["seguridad", "security", ".env", "secret", "docker", "deploy", "ci/cd"] if t in texto]
        if menciones:
            agregar_hallazgo(
                "Documentación de seguridad",
                "README con instrucciones operativas",
                "README contiene algunas menciones relacionadas con operación/configuración.",
                "OK",
                f"README.md menciona: {', '.join(menciones)}",
                "Complementar con pasos claros de configuración segura, variables de entorno y despliegue.",
            )
        else:
            agregar_hallazgo(
                "Documentación de seguridad",
                "README con instrucciones operativas",
                "README existe, pero no parece documentar aspectos de seguridad/operación.",
                "Bajo",
                "README.md sin menciones claras a seguridad, .env, secrets o despliegue.",
                "Agregar sección de configuración segura y variables de entorno requeridas.",
            )
    else:
        agregar_hallazgo(
            "Documentación de seguridad",
            "README",
            "No se detectó README.md.",
            "Medio",
            "README.md ausente.",
            "Documentar ejecución, configuración, variables de entorno y medidas de seguridad.",
        )

revisar_github_actions(repo_dir)
revisar_documentacion_seguridad(repo_dir)
print("Revisión CI/CD y documentación completada")

# Revisión de logs del pipeline
PATRON_LOGS = re.compile(r"(?i)(\.log$|logs?/|log_|_log)")
PATRONES_EVENTOS_LOG = {
    "CRITICAL": re.compile(r"(?i)critical|fatal|panic"),
    "ERROR": re.compile(r"(?i)error|exception|traceback"),
    "WARNING": re.compile(r"(?i)warning|warn"),
    "ACCESS_DENIED": re.compile(r"(?i)unauthorized|forbidden|access denied|permission denied|authentication failed|login failed"),
    "RETRY_FAILURE": re.compile(r"(?i)retry|timeout|connection refused|connection failed"),
}


def revisar_logs(repo_dir: Path):
    candidatos = []
    for p in repo_dir.rglob("*"):
        if p.is_file() and not any(part in CARPETAS_OMITIDAS for part in p.parts):
            rel = ruta_relativa(p, repo_dir)
            if PATRON_LOGS.search(rel) and es_archivo_texto(p):
                candidatos.append(p)

    if not candidatos:
        agregar_hallazgo(
            "Logs y monitoreo",
            "Disponibilidad de logs",
            "No se detectaron archivos de log versionados o carpeta logs.",
            "Informativo",
            "No hay logs locales en el repositorio.",
            "Documentar dónde se generan los logs del pipeline y cómo revisarlos.",
            "Configurar logging estructurado y evitar subir logs con datos sensibles.",
        )
        return

    for log in candidatos[:50]:
        rel = ruta_relativa(log, repo_dir)
        texto = leer_texto_seguro(log, max_bytes=1_000_000)
        conteo = {nombre: len(patron.findall(texto)) for nombre, patron in PATRONES_EVENTOS_LOG.items()}
        total_eventos = sum(conteo.values())
        if conteo["CRITICAL"] or conteo["ACCESS_DENIED"]:
            sev = "Alto"
        elif conteo["ERROR"]:
            sev = "Medio"
        elif total_eventos:
            sev = "Bajo"
        else:
            sev = "OK"
        agregar_hallazgo(
            "Logs y monitoreo",
            "Eventos relevantes en logs",
            f"Eventos detectados en log: {total_eventos}",
            sev,
            f"{rel} | {conteo}",
            "Revisar eventos críticos, accesos fallidos y errores recurrentes. Evitar versionar logs con datos sensibles.",
            "Centralizar logs y definir alertas para ERROR/CRITICAL/accesos fallidos.",
        )

revisar_logs(repo_dir)
print("Revisión de logs completada")

# Revisión opcional del entorno local
def revisar_puertos_localhost():
    if not EJECUTAR_REVISION_LOCALHOST:
        agregar_hallazgo(
            "Accesos y configuración",
            "Puertos locales",
            "Revisión de puertos locales no ejecutada por configuración.",
            "Informativo",
            "EJECUTAR_REVISION_LOCALHOST=False",
            "Activar solo si se necesita revisar el entorno local propio.",
        )
        return

    sistema = platform.system().lower()
    if "windows" in sistema:
        cmd = ["netstat", "-ano"]
    else:
        cmd = ["ss", "-tulnp"] if shutil.which("ss") else ["netstat", "-tulnp"]
    res = ejecutar_comando(cmd, timeout=60)
    salida = res["stdout"] + "\n" + res["stderr"]
    encontrados = []
    for puerto in PUERTOS_SENSIBLES:
        if re.search(rf"[:.]({re.escape(puerto)})\b", salida):
            encontrados.append(puerto)
    if encontrados:
        agregar_hallazgo(
            "Accesos y configuración",
            "Puertos locales sensibles",
            "Se detectaron puertos sensibles escuchando en el entorno local.",
            "Medio",
            f"Puertos detectados: {', '.join(encontrados)}",
            "Confirmar que estos servicios sean necesarios y que no estén expuestos públicamente.",
            "Restringir a localhost, firewall o red interna según corresponda.",
            "netstat/ss",
        )
    else:
        agregar_hallazgo(
            "Accesos y configuración",
            "Puertos locales sensibles",
            "No se detectaron puertos sensibles de la lista base escuchando localmente.",
            "OK",
            "Revisión local ejecutada sin coincidencias sensibles.",
            "Mantener revisión antes de despliegues.",
            herramienta="netstat/ss",
        )

revisar_puertos_localhost()
print("Revisión local opcional completada")

# Consolidación de hallazgos
df_hallazgos = pd.DataFrame(hallazgos)
if df_hallazgos.empty:
    df_hallazgos = pd.DataFrame([{
        "categoría": "General",
        "control evaluado": "Revisión general",
        "resultado": "No se generaron hallazgos.",
        "severidad": "Informativo",
        "evidencia": "Sin datos",
        "recomendación": "Verificar ejecución de celdas anteriores.",
        "acción sugerida": "Reejecutar notebook desde el inicio.",
        "herramienta": "Notebook",
    }])

df_hallazgos["orden_severidad"] = df_hallazgos["severidad"].map(SEVERIDAD_ORDEN).fillna(0)
df_hallazgos = df_hallazgos.sort_values(["orden_severidad", "categoría", "control evaluado"], ascending=[False, True, True]).drop(columns=["orden_severidad"])

df_hallazgos.to_csv(SALIDA_DIR / "hallazgos_seguridad.csv", index=False, encoding="utf-8-sig")

display(df_hallazgos)

# Resumen ejecutivo y puntaje referencial de seguridad
# Inicio 100 puntos (se descontarán puntos segun vulnerabilidades)
PENALIZACION = {
    "Crítico": 35,
    "Alto": 22,
    "Medio": 10,
    "Bajo": 4,
    "Informativo": 0,
    "OK": 0,
}

PESOS_CATEGORIA = {
    "Credenciales y secretos": 1.3,
    "Accesos y configuración": 1.2,
    "Dependencias y vulnerabilidades": 1.1,
    "Docker y entorno de ejecución": 1.0,
    "CI/CD y GitHub": 1.0,
    "Logs y monitoreo": 0.8,
    "Documentación de seguridad": 0.6,
}

# Conteo por severidad
resumen_sev = (
    df_hallazgos.groupby("severidad", as_index=False)
    .size()
    .rename(columns={"size": "cantidad"})
)
resumen_sev["orden"] = resumen_sev["severidad"].map(SEVERIDAD_ORDEN).fillna(0)
resumen_sev = resumen_sev.sort_values("orden", ascending=False).drop(columns="orden")

# Puntaje global
penalizacion_total = 0
for _, row in df_hallazgos.iterrows():
    penalizacion_total += PENALIZACION.get(row["severidad"], 0) * PESOS_CATEGORIA.get(row["categoría"], 1.0)

puntaje_global = max(0, round(100 - penalizacion_total, 1))

if puntaje_global >= 85:
    nivel = "Bueno"
elif puntaje_global >= 70:
    nivel = "Aceptable con mejoras"
elif puntaje_global >= 50:
    nivel = "Riesgo medio"
else:
    nivel = "Riesgo alto"

# Puntaje por categoría
filas_categoria = []
for categoria in CATEGORIAS:
    df_cat = df_hallazgos[df_hallazgos["categoría"] == categoria]
    if df_cat.empty:
        score = 100
    else:
        penal = sum(PENALIZACION.get(s, 0) for s in df_cat["severidad"])
        score = max(0, round(100 - penal, 1))
    filas_categoria.append({"categoría": categoria, "puntaje": score})

df_puntaje_categoria = pd.DataFrame(filas_categoria)
df_puntaje_categoria.to_csv(SALIDA_DIR / "puntaje_seguridad_por_categoria.csv", index=False, encoding="utf-8-sig")

print(f"Puntaje global referencial: {puntaje_global}/100")
print(f"Nivel: {nivel}")
display(resumen_sev)
display(df_puntaje_categoria)

# Visualizaciones de diagnóstico
# Gráfico de barras: hallazgos por severidad
orden = ["Crítico", "Alto", "Medio", "Bajo", "Informativo", "OK"]
plot_data = resumen_sev.set_index("severidad").reindex(orden).fillna(0).reset_index()

plt.figure(figsize=(9, 5))
plt.bar(plot_data["severidad"], plot_data["cantidad"])
plt.title("Hallazgos por severidad")
plt.xlabel("Severidad")
plt.ylabel("Cantidad de hallazgos")
plt.xticks(rotation=30, ha="right")
plt.tight_layout()
plt.savefig(SALIDA_DIR / "hallazgos_por_severidad.png", dpi=150, bbox_inches="tight")
plt.show()

# Gráfico radial: puntaje por categoría
categorias = df_puntaje_categoria["categoría"].tolist()
valores = df_puntaje_categoria["puntaje"].tolist()

angulos = np.linspace(0, 2 * np.pi, len(categorias), endpoint=False).tolist()
valores_cerrados = valores + valores[:1]
angulos_cerrados = angulos + angulos[:1]

plt.figure(figsize=(8, 8))
ax = plt.subplot(111, polar=True)
ax.plot(angulos_cerrados, valores_cerrados, linewidth=2)
ax.fill(angulos_cerrados, valores_cerrados, alpha=0.15)
ax.set_xticks(angulos)
ax.set_xticklabels(categorias, fontsize=9)
ax.set_yticks([20, 40, 60, 80, 100])
ax.set_ylim(0, 100)
ax.set_title("Madurez de seguridad por categoría", pad=20)
plt.tight_layout()
plt.savefig(SALIDA_DIR / "radar_madurez_seguridad.png", dpi=150, bbox_inches="tight")
plt.show()

# Matriz de recomendaciones
def prioridad_desde_severidad(sev):
    if sev in ["Crítico", "Alto"]:
        return "Prioridad 1 - Corregir antes del despliegue"
    if sev == "Medio":
        return "Prioridad 2 - Planificar corrección"
    if sev == "Bajo":
        return "Prioridad 3 - Mejora recomendada"
    if sev == "OK":
        return "Mantener control"
    return "Revisión manual / informativo"


df_recomendaciones = df_hallazgos.copy()
df_recomendaciones["prioridad"] = df_recomendaciones["severidad"].apply(prioridad_desde_severidad)
df_recomendaciones = df_recomendaciones[[
    "prioridad", "severidad", "categoría", "control evaluado", "resultado", "recomendación", "acción sugerida", "evidencia"
]]

df_recomendaciones.to_csv(SALIDA_DIR / "recomendaciones_seguridad.csv", index=False, encoding="utf-8-sig")
display(df_recomendaciones)

# Checklist para completar evidencia
checklist_manual = [
    {
        "aspecto": "Variables de entorno en despliegue",
        "evidencia esperada": "Captura o descripción de variables configuradas en plataforma, sin mostrar valores secretos.",
        "estado": "Pendiente completar",
        "observación": "Verificar que las credenciales no estén en el repositorio y sí en secrets/variables protegidas.",
    },
    {
        "aspecto": "Permisos de usuarios o servicios",
        "evidencia esperada": "Descripción de roles mínimos para BD, cloud, GitHub y despliegue.",
        "estado": "Pendiente completar",
        "observación": "Aplicar principio de privilegios mínimos.",
    },
    {
        "aspecto": "Puertos expuestos en despliegue real",
        "evidencia esperada": "Lista de puertos abiertos y justificación de cada uno.",
        "estado": "Pendiente completar",
        "observación": "Bases de datos no deberían quedar públicas sin control.",
    },
    {
        "aspecto": "Logs del entorno real",
        "evidencia esperada": "Resumen de errores, advertencias y accesos fallidos, sin datos sensibles.",
        "estado": "Pendiente completar",
        "observación": "Revisar logs del pipeline, contenedores y servicios asociados.",
    },
    {
        "aspecto": "Branch protection / revisión de cambios",
        "evidencia esperada": "Indicar si main/master requiere PR, revisión y checks de CI.",
        "estado": "Pendiente completar",
        "observación": "Evitar modificaciones directas no revisadas sobre ramas principales.",
    },
    {
        "aspecto": "Rotación de secretos",
        "evidencia esperada": "Indicar si se rotaron credenciales expuestas o de prueba.",
        "estado": "Pendiente completar",
        "observación": "Si una clave estuvo en Git, debe considerarse comprometida.",
    },
]

df_checklist_manual = pd.DataFrame(checklist_manual)
df_checklist_manual.to_csv(SALIDA_DIR / "checklist_manual_seguridad.csv", index=False, encoding="utf-8-sig")
display(df_checklist_manual)

# Generación automática de informe (markdown)
def tabla_markdown(df: pd.DataFrame, max_rows=30):
    if len(df) > max_rows:
        df = df.head(max_rows).copy()
    return df.to_markdown(index=False)

resumen_top = df_recomendaciones[df_recomendaciones["severidad"].isin(["Crítico", "Alto", "Medio"])].head(15)
if resumen_top.empty:
    resumen_top = df_recomendaciones.head(10)

informe = f"""
# Informe de evaluación de seguridad del pipeline DataOps

## 1. Identificación

| Campo | Valor |
|---|---|
| Estudiante | {NOMBRE_ESTUDIANTE} |
| Sección / curso | {SECCION} |
| Proyecto | {NOMBRE_PROYECTO} |
| Repositorio evaluado | {REPO_URL} |
| Fecha de análisis | {FECHA_ANALISIS} |
| Carpeta local auditada | {repo_dir.resolve()} |

## 2. Objetivo del análisis

Evaluar la seguridad básica del pipeline DataOps y su entorno de ejecución, revisando configuraciones inseguras, credenciales expuestas, puertos o servicios publicados, dependencias vulnerables, configuraciones Docker/CI-CD y evidencia disponible en logs.

## 3. Resumen ejecutivo

- Puntaje global referencial: **{puntaje_global}/100**.
- Nivel interpretativo: **{nivel}**.
- Total de hallazgos: **{len(df_hallazgos)}**.

### Hallazgos por severidad

{tabla_markdown(resumen_sev)}

## 4. Hallazgos priorizados

{tabla_markdown(resumen_top, max_rows=15)}

## 5. Puntaje por categoría

{tabla_markdown(df_puntaje_categoria)}

## 6. Recomendaciones generales

1. Mantener credenciales fuera del repositorio y utilizar variables de entorno, GitHub Secrets o gestores de secretos.
2. Revisar puertos publicados en Docker Compose y restringir bases de datos a redes internas o localhost.
3. Mantener dependencias actualizadas y automatizar revisión con Dependabot, pip-audit, npm audit o Trivy.
4. Ejecutar contenedores con usuarios no root y permisos mínimos.
5. Definir permisos explícitos en workflows de GitHub Actions.
6. Documentar logs, monitoreo y respuesta ante errores críticos o accesos fallidos.
7. Agregar SECURITY.md, CODEOWNERS y protección de ramas si el proyecto será mantenido por equipo.

## 7. Checklist manual pendiente

{tabla_markdown(df_checklist_manual)}

## 8. Archivos generados como evidencia

- `hallazgos_seguridad.csv`
- `recomendaciones_seguridad.csv`
- `puntaje_seguridad_por_categoria.csv`
- `checklist_manual_seguridad.csv`
- `hallazgos_por_severidad.png`
- `radar_madurez_seguridad.png`

"""

ruta_informe = SALIDA_DIR / "informe_seguridad_pipeline.md"
ruta_informe.write_text(informe.strip(), encoding="utf-8")

print("Informe generado en:", ruta_informe.resolve())
print("Archivos de evidencia generados en:", SALIDA_DIR.resolve())

# Vista del informe generado
from IPython.display import Markdown, display

display(Markdown((SALIDA_DIR / "informe_seguridad_pipeline.md").read_text(encoding="utf-8")))