# -*- coding: utf-8 -*-
"""Pruebas de Rendimiento - Caso2 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uz3SUD49QQFubZ1GoHOYdNyPCjG0rxeJ
"""

import pandas as pd
from sklearn import datasets
import numpy as np
from collections import Counter
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
from sklearn.pipeline import Pipeline
import numpy as np
import seaborn as sns
import scipy
import matplotlib.pyplot as plt
import sklearn.tree # Árboles de decisión
import sklearn.ensemble # Ensambles de modelos
import sklearn.model_selection
import sklearn.decomposition # Módulo donde encontramos el análisis de componentes principales
from sklearn import datasets
from collections import Counter
from statsmodels.stats.multicomp import pairwise_tukeyhsd

# Instrumentación para medición del rendimiento
import os
import time
import math
import traceback
import threading
from contextlib import contextmanager
from datetime import datetime

try:
    import psutil
except ImportError:
    psutil = None

try:
    import resource
except Exception:
    resource = None

registros_rendimiento = []

def _cpu_seconds_total():
    """
    CPU acumulada del proceso actual.
    En sistemas Unix/Linux intenta incluir también procesos hijos,
    útil para cross_val_score con n_jobs=-1.
    """
    total = time.process_time()
    if resource is not None:
        try:
            hijos = resource.getrusage(resource.RUSAGE_CHILDREN)
            total += hijos.ru_utime + hijos.ru_stime
        except Exception:
            pass
    return total

def _rss_mb_arbol_procesos():
    """
    Memoria RSS aproximada del proceso actual y, si existen, procesos hijos.
    """
    if psutil is None:
        return float("nan")
    try:
        proceso = psutil.Process(os.getpid())
        total = proceso.memory_info().rss
        for hijo in proceso.children(recursive=True):
            try:
                total += hijo.memory_info().rss
            except Exception:
                pass
        return total / (1024 ** 2)
    except Exception:
        return float("nan")

def _fmt_num(valor, decimales=3):
    if valor is None:
        return "No aplica"
    try:
        if math.isnan(valor):
            return "No disponible"
    except Exception:
        pass
    return f"{valor:.{decimales}f}"

@contextmanager
def medir_rendimiento(operacion, detalle="", unidades=None, unidad_nombre="registros"): ######### contextualizar código para ejecutar función
    """
    Mide el rendimiento de un bloque de código.

    Parámetros:
    - operacion: nombre del punto clave del pipeline.
    - detalle: descripción breve de lo que se ejecuta.
    - unidades: cantidad procesada, cuando aplica.
    - unidad_nombre: nombre de la unidad procesada, por ejemplo registros, filas, folds.
    """
    inicio_fecha = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    t0 = time.perf_counter()
    cpu0 = _cpu_seconds_total()
    mem0 = _rss_mb_arbol_procesos()
    muestras_memoria = []
    if not math.isnan(mem0):
        muestras_memoria.append(mem0)

    detener_muestreo = threading.Event()

    def _muestrear_memoria():
        while not detener_muestreo.is_set():
            mem = _rss_mb_arbol_procesos()
            if not math.isnan(mem):
                muestras_memoria.append(mem)
            time.sleep(0.10)

    hilo = None
    if psutil is not None:
        hilo = threading.Thread(target=_muestrear_memoria, daemon=True)
        hilo.start()

    estado = "OK"
    error = ""
    try:
        yield
    except Exception as exc:
        estado = "ERROR"
        error = f"{type(exc).__name__}: {exc}"
        raise
    finally:
        detener_muestreo.set()
        if hilo is not None:
            hilo.join(timeout=0.3)

        t1 = time.perf_counter()
        cpu1 = _cpu_seconds_total()
        mem1 = _rss_mb_arbol_procesos()

        tiempo_s = t1 - t0
        cpu_s = max(cpu1 - cpu0, 0)
        cpu_pct = (cpu_s / tiempo_s) * 100 if tiempo_s > 0 else float("nan")

        if math.isnan(mem0) or math.isnan(mem1):
            delta_mem = float("nan")
        else:
            delta_mem = mem1 - mem0

        pico_mem = max(muestras_memoria) if muestras_memoria else mem1

        if unidades is not None and unidades != 0:
            try:
                latencia_ms = (tiempo_s / unidades) * 1000
            except Exception:
                latencia_ms = float("nan")
        else:
            latencia_ms = float("nan")

        registros_rendimiento.append({
            "Fecha/hora": inicio_fecha,
            "Operación": operacion,
            "Detalle": detalle,
            "Tiempo ejecución (s)": tiempo_s,
            "CPU proceso aprox. (%)": cpu_pct,
            "CPU proceso (s)": cpu_s,
            "RAM inicial (MB)": mem0,
            "RAM final (MB)": mem1,
            "RAM pico aprox. (MB)": pico_mem,
            "RAM delta (MB)": delta_mem,
            "Unidades procesadas": unidades,
            "Unidad": unidad_nombre,
            "Latencia aprox. (ms/unidad)": latencia_ms,
            "Estado": estado,
            "Log": "Sin errores" if estado == "OK" else error
        })

def actualizar_unidades_operacion(operacion, unidades, unidad_nombre="registros"):
    """
    Permite actualizar la cantidad de unidades procesadas cuando se conoce después de ejecutar el bloque.
    """
    for registro in reversed(registros_rendimiento):
        if registro["Operación"] == operacion:
            registro["Unidades procesadas"] = unidades
            registro["Unidad"] = unidad_nombre
            tiempo_s = registro["Tiempo ejecución (s)"]
            registro["Latencia aprox. (ms/unidad)"] = (tiempo_s / unidades) * 1000 if unidades else float("nan")
            break

def registrar_estabilidad_cv(operacion, scores):
    """
    Agrega indicadores de estabilidad para operaciones de validación cruzada.
    """
    import numpy as np

    scores = np.array(scores)
    media = float(np.mean(scores))
    desviacion = float(np.std(scores))
    minimo = float(np.min(scores))
    maximo = float(np.max(scores))
    variabilidad_pct = (desviacion / media) * 100 if media != 0 else float("nan")

    if variabilidad_pct < 5:
        estabilidad = "Alta: baja variabilidad entre folds"
    elif variabilidad_pct < 10:
        estabilidad = "Media: variabilidad moderada entre folds"
    else:
        estabilidad = "Revisar: alta variabilidad entre folds"

    for registro in reversed(registros_rendimiento):
        if registro["Operación"] == operacion:
            registro["F1 promedio CV"] = media
            registro["F1 desviación CV"] = desviacion
            registro["F1 mínimo CV"] = minimo
            registro["F1 máximo CV"] = maximo
            registro["Variabilidad CV (%)"] = variabilidad_pct
            registro["Estabilidad CV"] = estabilidad
            break

print("Instrumentación de rendimiento cargada correctamente.")

# Definición de funciones
def calcula_metricas(nombre_algoritmo,y_test,y_pred):
### CLASE POSITIVA (1) ###
    #Calculo la precisión del modelo
    from sklearn.metrics import precision_score
    precision = precision_score(y_test, y_pred)

    #Calculo la exactitud del modelo
    from sklearn.metrics import accuracy_score
    exactitud = accuracy_score(y_test, y_pred)

    #Calculo la sensibilidad del modelo
    from sklearn.metrics import recall_score
    sensibilidad = recall_score(y_test, y_pred)

    #Calculo el Puntaje F1 del modelo
    from sklearn.metrics import f1_score
    puntajef1 = f1_score(y_test, y_pred)

    #Calculo la curva ROC - AUC del modelo
    from sklearn.metrics import roc_auc_score
    roc_auc = roc_auc_score(y_test, y_pred)

### CLASE NEGATIVA (0) ###
    from sklearn.metrics import confusion_matrix
    labels = [1, 0]
    cm = confusion_matrix(y_test, y_pred, labels = labels)
    tp,fn,fp,tn = cm.ravel()

    #True Negative Rate / specificity
    TNR_recall_espec = round(tn/(tn+fp),6)

    #Negative Predictive Value
    NPV_precision = round(tn/(tn+fn),6)

    #Cálculo del F1 para la clase negativa
    F1_neg = round(2 * (NPV_precision * TNR_recall_espec) / (NPV_precision + TNR_recall_espec),2)

    ## Vector de Desempeño - Resumen de Métricas del Modelo
    df_1 = pd.DataFrame({'Modelo': [nombre_algoritmo],'Clase ':[1],'Exactitud': [exactitud],'Precisión': [precision],
                   'Sensibilidad': [sensibilidad], 'F1': [puntajef1],'AUC': [roc_auc]})
    df_2 = pd.DataFrame({'Modelo': '','Clase ':[0],'Exactitud': '','Precisión': [NPV_precision],
                   'Sensibilidad': [TNR_recall_espec], 'F1': [F1_neg],'AUC': ''})
   # df = df_1.append(df_2, ignore_index = True)
    df = pd.concat([df_1, df_2], ignore_index=True)

    return df

# Matriz de confusión
def matriz_confusion(y_test,y_pred):
    import matplotlib.pyplot as plt
    import seaborn as sns
    #Verifico la matriz de Confusión
    from sklearn.metrics import confusion_matrix
    matriz = confusion_matrix(y_test, y_pred,labels=[1, 0])

    ax = sns.heatmap(matriz, annot=True, cmap='Blues', fmt='g')
    ax.set_title('Matriz de Confusión\n\n');
    ax.set_xlabel('\nPredicción')
    ax.set_ylabel('Real ');

    ## Ticket labels - List must be in alphabetical order
    ax.xaxis.set_ticklabels(['True','False'])
    ax.yaxis.set_ticklabels(['True','False'])

    ## Display the visualization of the Confusion Matrix.
    plt.show()

# Se omite el proceso de Balanceo de clases """"""""""""""""""""""
  # Control con Hiperparámetro

#Synthetic Minority Oversampling Technique_ + Submuestro de la clase mayoritaria + Balanceo parcial del dataset
def SMOTE_RUS (X_train,y_train,sample_smote,sample_rus,balancear=True):
    if balancear:
      import imblearn
      sm = imblearn.over_sampling.SMOTE(sampling_strategy=sample_smote,random_state=11)
      rus = imblearn.under_sampling.RandomUnderSampler(sampling_strategy=sample_rus,random_state=11)
      steps = [('SMOTE', sm), ('RUS', rus)] # Ponemos ambos pasos
      sm_rus = imblearn.pipeline.Pipeline(steps=steps) # Creamos un pipeline para realizar ambas tareas
      X_train_sm_rus, y_train_sm_rus = sm_rus.fit_resample(X_train, y_train)
      return X_train_sm_rus,y_train_sm_rus, sm_rus
    else: # Caso negativo:
      return X_train, y_train, None # Entregar None en ves del pipeline, datos se mantienen

#Dibuja los scores obtenidos como proceso de evaluación iterativo, recibe los resultados y el valor ideal
def plot_scores(scores, ideal):
    import matplotlib.pyplot as plt
    # creating the dataset
    dic_scores = dict(enumerate(scores.flatten(), 1))
    k = list(dic_scores.keys())
    valores = list(dic_scores.values())

    fig = plt.figure(figsize = (10, 5))

    # creating the xy plot
  #  plt.xlim( [ min(k), max(k) ] )          # Plot from x=0 to x=80.
  #  plt.ylim( [ min(scores), 1 ] )
   #Gráfico XY de los scores vs K-folds
    plt.text(max(k)/2,max(valores)+0.010,'Comportamiento del score', color='steelblue')
    plt.plot(k, valores, color ='steelblue')

    #Mustra línea de umbral establecida
    plt.text(max(k)/2,ideal-0.010,'Umbral de hipótesis',color='mediumblue')
    plt.plot(k,[ideal for _ in range(len(k))],color='mediumblue')

    #Muestra la línea promedio obtenida
    plt.text(max(k)/2,scores.mean()-0.010,'Score promedio',color='brown')
    plt.text(max(k)/2,scores.mean()-0.020, round(scores.mean(),6),color='brown')

    plt.plot(k,[scores.mean() for _ in range(len(k))],color='brown', linestyle='dashed')
    plt.xlabel("k-folds")
    plt.ylabel("score")
    plt.suptitle("Scores de algoritmo evaluado mediante k-fold estratificado")
    plt.title("score ideal del proyecto F1 = 0.8")
    plt.show()

#Carga de datos depurados
with medir_rendimiento("Carga de datos", detalle='pd.read_csv("datos_02_bank_validados.csv")'): ## Agregar nombre a la tarea, contabilización "with" contextualización de medidas de rendimiento
    data = pd.read_csv("datos_02_bank_validados.csv")

actualizar_unidades_operacion("Carga de datos", len(data), "filas")

df2 = data.groupby(['deposit'])['deposit'].count()
df2

# Separar las variables dependientes de la independientes
with medir_rendimiento("Preparación de variables X/y", detalle="Separación de variable objetivo y variables predictoras", unidades=len(data), unidad_nombre="filas"):
    y = data['deposit']
    X = data.drop(['deposit','duration','fecha_procesamiento'], axis = 1)

    #Captura los nombres de las variables independientes
    cols = X.columns

#Cuenta la cantidad de registros por cada clase
Counter(y)

# Separación de datos Train / Test
from sklearn.model_selection import train_test_split

# Se separa el dataset en entrenamiento y prueba.
# IMPORTANTE:
# El conjunto de prueba queda reservado para la evaluación final del modelo.
# Por eso, la validación cruzada se realizará solamente sobre X_train_raw e y_train_raw.
with medir_rendimiento("Separación Train/Test", detalle="train_test_split estratificado", unidades=len(X), unidad_nombre="filas"):
    X_train, X_test, y_train, y_test = train_test_split( ###########################
        X,
        y,
        test_size=0.2,
        random_state=0,
        stratify=y
    )

# Escalamiento de datos
from sklearn.preprocessing import MinMaxScaler

# IMPORTANTE:
# El escalador se ajusta solamente con el conjunto de entrenamiento original.
# Así se evita fuga de datos desde el conjunto de prueba.
escalar = MinMaxScaler()
#################################################################################
with medir_rendimiento("Escalamiento MinMax", detalle="fit_transform en train y transform en test", unidades=len(X_train) + len(X_test), unidad_nombre="filas"):
    X_train = escalar.fit_transform(X_train)  # aprende mínimos y máximos solo desde entrenamiento
    X_test = escalar.transform(X_test)        # aplica la misma escala al conjunto de prueba

# Cuenta la cantidad de registros por cada clase del conjunto de entrenamiento original
Counter(y_train)

# Zona de balanceo de clases

# En este caso de estudio, no se requiere balanceo de clases!!!
# Invocar función SMOTE + RUS solamente sobre el conjunto de entrenamiento escalado
# IMPORTANTE:
# El balanceo no se aplica sobre X_test, porque el conjunto de prueba debe representar datos no vistos.
#with medir_rendimiento("Balanceo SMOTE + RUS", detalle="SMOTE(sampling_strategy=0.5) + RandomUnderSampler(sampling_strategy=0.75)", unidades=len(X_train), unidad_nombre="filas train originales"):
  #  X_train, y_train, pipeline_balanceo = SMOTE_RUS(X_train, y_train_raw, 0.5, 0.75)

a#ctualizar_unidades_operacion("Balanceo SMOTE + RUS", len(y_train), "filas train balanceadas")

# Cuenta la cantidad de registros del set de entrenamiento post balanceo
#Counter(y_train)

# Arboles de # Instanciar el clasificador basado en Arboles de decisión
from sklearn.tree import DecisionTreeClassifier
tree_clf = DecisionTreeClassifier(max_depth=8,criterion = 'entropy')

#Entreno el modelo
with medir_rendimiento("Entrenamiento Decision Tree", detalle="tree_clf.fit(X_train, y_train)", unidades=len(X_train), unidad_nombre="filas train balanceadas"):
    tree_clf.fit(X_train, y_train)

#Realizo una predicción
with medir_rendimiento("Predicción Decision Tree", detalle="tree_clf.predict(X_test)", unidades=len(X_test), unidad_nombre="filas test"):
    y_pred = tree_clf.predict(X_test)

#Calcula y despliega la matriz de confusión
matriz_confusion(y_test,y_pred)

#Obtiene las métricas del modelo
with medir_rendimiento("Métricas Decision Tree", detalle="precision, accuracy, recall, f1 y matriz de métricas", unidades=len(y_test), unidad_nombre="filas test"):
    df_metricas_tree = calcula_metricas('Tree',y_test,y_pred)

#df_metricas_tree.style.hide_index()
df_metricas_tree.style.hide(axis="index")

# Evaluación de estabilidad del rendimiento del modelo en múltiples entrenamientos
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from numpy import mean

# Pipeline completo para validación cruzada:
# En cada fold se ajusta el escalador solo con el subconjunto de entrenamiento del fold.
# Luego se aplica SMOTE + RUS solo sobre ese subconjunto de entrenamiento.
# Finalmente se entrena y evalúa el modelo evitando fuga de datos.
#
# IMPORTANTE:
# Como existe un conjunto de prueba final separado, la validación cruzada se realiza
# solamente sobre X_train_raw e y_train_raw, no sobre X e y completos.
pipeline_tree = Pipeline([
    ('scaler', MinMaxScaler()),
    #('SMOTE', SMOTE(sampling_strategy=0.5, random_state=11)),
    #('RUS', RandomUnderSampler(sampling_strategy=0.75, random_state=11)),
    ('tree', DecisionTreeClassifier(max_depth=8, criterion='entropy'))
])

cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

with medir_rendimiento("Validación cruzada Decision Tree", detalle="RepeatedStratifiedKFold 10x3 con pipeline completo", unidades=30, unidad_nombre="folds"): ###########!!!
    tree_scores = cross_val_score(
        pipeline_tree,
        X_train,
        y_train,
        scoring='f1',
        cv=cv,
        n_jobs=-1 # n_jobs, hiperparámetro cuantos cores de la CPU se usará para esta función (-1 significa que se usara su totalidad)
    )

registrar_estabilidad_cv("Validación cruzada Decision Tree", tree_scores)

score = round(tree_scores.mean(), 6)
print('F1 promedio: %.3f' % score)

#Dibuja los scores obtenidos como proceso de evaluación iterativo, recibe los resultados y el valor ideal
plot_scores(tree_scores, 0.8)

# Regresión Logística
#Defino el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
lr_clf = LogisticRegression()

#Entreno el modelo
with medir_rendimiento("Entrenamiento Regresión Logística", detalle="lr_clf.fit(X_train, y_train)", unidades=len(X_train), unidad_nombre="filas train balanceadas"):
    lr_clf.fit(X_train, y_train)

#Realizo una predicción
with medir_rendimiento("Predicción Regresión Logística", detalle="lr_clf.predict(X_test)", unidades=len(X_test), unidad_nombre="filas test"):
    y_pred = lr_clf.predict(X_test)

#Calcula y despliega la matriz de confusión
matriz_confusion(y_test,y_pred)

#Obtiene las métricas del modelo
with medir_rendimiento("Métricas Regresión Logística", detalle="precision, accuracy, recall, f1 y matriz de métricas", unidades=len(y_test), unidad_nombre="filas test"):
    df_metricas_lr = calcula_metricas('Regresión Logística',y_test,y_pred)

#df_metricas_lr.style.hide_index()
df_metricas_lr.style.hide(axis="index")

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from numpy import mean

# Pipeline completo para Regresión Logística en validación cruzada.
# El escalado y el balanceo se realizan dentro de cada fold, evitando fuga de datos.
#
# IMPORTANTE:
# Como existe un conjunto de prueba final separado, la validación cruzada se realiza
# solamente sobre X_train_raw e y_train_raw, no sobre X e y completos.
pipeline_lr = Pipeline([
    ('scaler', MinMaxScaler()),
    #('SMOTE', SMOTE(sampling_strategy=0.5, random_state=11)),
    #('RUS', RandomUnderSampler(sampling_strategy=0.75, random_state=11)),
    ('lr', LogisticRegression(max_iter=1000))
])

cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

with medir_rendimiento("Validación cruzada Regresión Logística", detalle="RepeatedStratifiedKFold 10x3 con pipeline completo", unidades=30, unidad_nombre="folds"):
    lr_scores = cross_val_score(
        pipeline_lr,
        X_train,
        y_train,
        scoring='f1',
        cv=cv,
        n_jobs=-1
    )

registrar_estabilidad_cv("Validación cruzada Regresión Logística", lr_scores)

score = round(lr_scores.mean(), 6)
print('F1 promedio: %.3f' % score)

#Dibuja los scores obtenidos como proceso de evaluación iterativo, recibe los resultados y el valor ideal
plot_scores(lr_scores, 0.8)

# Perceptrón multicapa
# Perceptrón Multicapa MLP (neuronas, capas)
# hidden_layer_sizes=(100,) indica una capa oculta con 100 neuronas.
from sklearn.neural_network import MLPClassifier
mlp_clf = MLPClassifier(random_state=0, hidden_layer_sizes=(100,), max_iter=1000)

#Entreno el modelo
with medir_rendimiento("Entrenamiento MLP", detalle="mlp_clf.fit(X_train, y_train)", unidades=len(X_train), unidad_nombre="filas train balanceadas"):
    mlp_clf.fit(X_train, y_train)

#Realizo una predicción
with medir_rendimiento("Predicción MLP", detalle="mlp_clf.predict(X_test)", unidades=len(X_test), unidad_nombre="filas test"):
    y_pred = mlp_clf.predict(X_test)

#Calcula y despliega la matriz de confusión
matriz_confusion(y_test,y_pred)

#Obtiene las métricas del modelo
with medir_rendimiento("Métricas MLP", detalle="precision, accuracy, recall, f1 y matriz de métricas", unidades=len(y_test), unidad_nombre="filas test"):
    df_metricas_mlp = calcula_metricas('MLP',y_test,y_pred)

df_metricas_mlp

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from sklearn.preprocessing import MinMaxScaler
from sklearn.neural_network import MLPClassifier
from numpy import mean

# Pipeline completo para MLP en validación cruzada.
# El escalado y el balanceo se realizan dentro de cada fold, evitando fuga de datos.
#
# IMPORTANTE:
# Como existe un conjunto de prueba final separado, la validación cruzada se realiza
# solamente sobre X_train_raw e y_train_raw, no sobre X e y completos.
pipeline_mlp = Pipeline([
    ('scaler', MinMaxScaler()),
    #('SMOTE', SMOTE(sampling_strategy=0.5, random_state=11)),
    #('RUS', RandomUnderSampler(sampling_strategy=0.75, random_state=11)),
    ('mlp', MLPClassifier(random_state=0, hidden_layer_sizes=(100,), max_iter=1000))
])

cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

with medir_rendimiento("Validación cruzada MLP", detalle="RepeatedStratifiedKFold 10x3 con pipeline completo", unidades=30, unidad_nombre="folds"):
    mlp_scores = cross_val_score(
        pipeline_mlp,
        X_train,
        y_train,
        scoring='f1',
        cv=cv,
        n_jobs=-1
    )

registrar_estabilidad_cv("Validación cruzada MLP", mlp_scores)

score = round(mlp_scores.mean(), 6)
print('F1 promedio: %.3f' % score)

#Dibuja los scores obtenidos como proceso de evaluación iterativo, recibe los resultados y el valor ideal
plot_scores(mlp_scores, 0.8)

# Evaluación
# Consolida todas las métricas obtenidas antes del proceso de validación cruzada
with medir_rendimiento("Consolidación métricas modelos", detalle="pd.concat de métricas Tree, LR y MLP", unidades=3, unidad_nombre="modelos"):
    df_metricas_consolidadas = pd.concat(
        [df_metricas_tree, df_metricas_lr, df_metricas_mlp],
        ignore_index=True
    )

df_metricas_consolidadas.style.hide(axis="index")

# Visualización radial de métricas por clase
# ============================================================
# GRÁFICOS RADIALES / TELARAÑA PARA MÉTRICAS POR CLASE
# ============================================================
# Esta celda usa la tabla df_metricas_consolidadas generada previamente.
# Se mantiene la programación original y solo se agregan funciones de visualización.
# Corrección aplicada:
# - Tanto la clase 1 como la clase 0 se grafican con las mismas métricas:
#   Exactitud, Precisión, Sensibilidad, F1 y AUC.
# - Si Exactitud y AUC vienen vacías en la fila de la clase 0, se completan
#   con el valor global correspondiente al mismo modelo.

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


METRICAS_RADAR = ["Exactitud", "Precisión", "Sensibilidad", "F1", "AUC"]


def preparar_metricas_radar(df_metricas):
    """
    Prepara la tabla consolidada para construir gráficos radar.

    Consideraciones:
    - El notebook original deja la columna Modelo vacía en la fila de la clase 0.
      Por eso se completa hacia abajo con ffill().
    - La columna 'Clase ' puede tener espacios en el nombre.
      Por eso se normalizan los nombres de columnas con strip().
    - Las métricas vacías se convierten a NaN.
    - Exactitud y AUC son métricas globales del modelo. Si están vacías para la clase 0,
      se completan desde la fila del mismo modelo para poder graficar las cinco métricas.
    """
    df_radar = df_metricas.copy()
    df_radar.columns = df_radar.columns.str.strip()

    # Completa el nombre del modelo cuando la segunda fila del mismo modelo viene vacía.
    if "Modelo" in df_radar.columns:
        df_radar["Modelo"] = df_radar["Modelo"].replace("", np.nan).ffill()

    # Normaliza la clase a número.
    if "Clase" in df_radar.columns:
        df_radar["Clase"] = pd.to_numeric(df_radar["Clase"], errors="coerce")

    # Convierte las métricas a numéricas, tolerando valores vacíos y coma decimal.
    for columna in METRICAS_RADAR:
        if columna in df_radar.columns:
            serie = df_radar[columna].replace("", np.nan)
            if serie.dtype == "object":
                serie = serie.astype(str).str.replace(",", ".", regex=False)
            df_radar[columna] = pd.to_numeric(serie, errors="coerce")

    # Exactitud y AUC suelen informarse una vez por modelo.
    # Se replican dentro de cada modelo para que tanto clase 1 como clase 0
    # puedan representarse con las cinco métricas solicitadas.
    for columna in ["Exactitud", "AUC"]:
        if columna in df_radar.columns and "Modelo" in df_radar.columns:
            df_radar[columna] = df_radar.groupby("Modelo", dropna=False)[columna].transform(
                lambda s: s.ffill().bfill()
            )

    return df_radar


def graficar_radar_metricas(df_metricas, clase, metricas=None, titulo=None, guardar_ruta=None):
    """
    Grafica un radar comparativo de métricas para una clase específica.

    Parámetros:
    - df_metricas: tabla consolidada de métricas.
    - clase: clase a graficar, normalmente 1 o 0.
    - metricas: lista opcional de métricas a incluir.
    - titulo: título opcional del gráfico.
    - guardar_ruta: si se indica una ruta, guarda el gráfico como imagen PNG.
    """
    df_radar = preparar_metricas_radar(df_metricas)

    if metricas is None:
        metricas = METRICAS_RADAR.copy()

    metricas = [m for m in metricas if m in df_radar.columns]
    datos_clase = df_radar[df_radar["Clase"] == int(clase)].copy()

    if datos_clase.empty:
        print(f"No hay datos disponibles para graficar la clase {clase}.")
        return None

    # Se exige que el radar tenga las cinco métricas solicitadas.
    metricas_faltantes = [m for m in METRICAS_RADAR if m not in datos_clase.columns]
    if metricas_faltantes:
        print(f"No se puede graficar la clase {clase}. Faltan columnas: {metricas_faltantes}")
        return None

    datos_clase = datos_clase[["Modelo"] + METRICAS_RADAR].dropna(subset=METRICAS_RADAR, how="any")
    if datos_clase.empty:
        print(
            f"No hay datos completos para graficar la clase {clase} con "
            f"Exactitud, Precisión, Sensibilidad, F1 y AUC."
        )
        return None

    # Ángulos del radar.
    n_metricas = len(METRICAS_RADAR)
    angulos = np.linspace(0, 2 * np.pi, n_metricas, endpoint=False).tolist()
    angulos += angulos[:1]

    fig = plt.figure(figsize=(8, 8))
    ax = plt.subplot(111, polar=True)

    # Deja la primera métrica arriba y avanza en sentido horario.
    ax.set_theta_offset(np.pi / 2)
    ax.set_theta_direction(-1)

    for _, fila in datos_clase.iterrows():
        valores = fila[METRICAS_RADAR].astype(float).tolist()
        valores += valores[:1]
        ax.plot(angulos, valores, linewidth=2, label=fila["Modelo"])
        ax.fill(angulos, valores, alpha=0.08)

    ax.set_xticks(angulos[:-1])
    ax.set_xticklabels(METRICAS_RADAR, fontsize=11)
    ax.set_ylim(0, 1)
    ax.set_yticks([0.2, 0.4, 0.6, 0.8, 1.0])
    ax.set_yticklabels(["0.2", "0.4", "0.6", "0.8", "1.0"], fontsize=9)
    ax.grid(True)

    if titulo is None:
        titulo = f"Comparación radial de métricas - Clase {clase}"

    ax.set_title(titulo, fontsize=14, pad=24)
    ax.legend(loc="upper right", bbox_to_anchor=(1.32, 1.12))

    plt.tight_layout()

    if guardar_ruta is not None:
        plt.savefig(guardar_ruta, dpi=300, bbox_inches="tight")
        print(f"Gráfico guardado en: {guardar_ruta}")

    plt.show()
    return fig


# Preparación de la tabla usada por los gráficos.
with medir_rendimiento(
    "Preparación datos gráficos radar",
    detalle="Normalizar columnas, completar modelo y completar Exactitud/AUC para clase 0",
    unidades=len(df_metricas_consolidadas),
    unidad_nombre="filas métricas"
):
    df_metricas_radar = preparar_metricas_radar(df_metricas_consolidadas)

# Muestra la tabla ya preparada para comprobar que ambas clases tienen las cinco métricas.
display(df_metricas_radar.style.hide(axis="index"))


# Gráfico radial para clase positiva 1.
with medir_rendimiento(
    "Gráfico radial clase 1",
    detalle="Radar con Exactitud, Precisión, Sensibilidad, F1 y AUC por modelo",
    unidades=3,
    unidad_nombre="modelos"
):
    graficar_radar_metricas(
        df_metricas_consolidadas,
        clase=1,
        metricas=METRICAS_RADAR,
        titulo="Desempeño comparativo de modelos - Clase 1: Se matricula",
        guardar_ruta="radar_metricas_clase_1.png"
    )


# Gráfico radial para clase negativa 0.
with medir_rendimiento(
    "Gráfico radial clase 0",
    detalle="Radar con Exactitud, Precisión, Sensibilidad, F1 y AUC por modelo",
    unidades=3,
    unidad_nombre="modelos"
):
    graficar_radar_metricas(
        df_metricas_consolidadas,
        clase=0,
        metricas=METRICAS_RADAR,
        titulo="Desempeño comparativo de modelos - Clase 0: No se matricula",
        guardar_ruta="radar_metricas_clase_0.png"
    )

print(
    "Corrección aplicada: ambos gráficos radiales usan Exactitud, Precisión, Sensibilidad, F1 y AUC. "
    "Para la clase 0, Exactitud y AUC se completan con el valor global del mismo modelo."
)

# Guardamos todos los resultados obtenido en los procesos de Cross Validation en una lista
scores = [tree_scores,lr_scores,mlp_scores]

#Nombres de los algoritmos utilizados
modelos = ["Decision Tree","Logistic Regression","Multilayer Perceptron"]

#Generar un diagrama de caja para ver la distribución de datos por cada predictor de matriculas.
#Usando boxplot, podemos detectar fácilmente las diferencias entre diferentes predictores de matriculas
plt.title("Distribución de scores por modelo")
plt.boxplot(scores,labels = modelos,patch_artist=True,
           boxprops=dict(facecolor="aliceblue",color ="dodgerblue"),
           whiskerprops=dict(color ="dodgerblue"),
           medianprops = dict(color ="darkred"),
           flierprops=dict(markeredgecolor ="royalblue"),
           capprops = dict(color ="dodgerblue"))

plt.xticks(rotation=45)
plt.show()

#Crea diccionario modelos y promedio del score
with medir_rendimiento("Cálculo F1 promedio por modelo", detalle="np.mean sobre scores de validación cruzada", unidades=3, unidad_nombre="modelos"):
    dict_score_means = dict(
        zip(
            modelos,
            map(
                np.mean,
                scores
            )
        )
    )
    df_score_means = pd.DataFrame.from_dict(dict_score_means,orient = 'index',  columns = ['Score mean'])

df_score_means.style.highlight_max(color = 'powderblue', axis = 0)

# ============================================================
# GUARDAR SOLO EL CLASIFICADOR CON MEJOR F1 USANDO JOBLIB
# Y SIMULAR UNA INFERENCIA POSTERIOR
# ============================================================

import numpy as np
import pandas as pd
import joblib

# ------------------------------------------------------------
# 1. Comparar los modelos según el F1 promedio de Cross Validation
# ------------------------------------------------------------

with medir_rendimiento("Selección mejor modelo", detalle="Comparación por F1 promedio de cross validation", unidades=3, unidad_nombre="modelos"):
    f1_tree = np.mean(tree_scores)
    f1_lr = np.mean(lr_scores)
    f1_mlp = np.mean(mlp_scores)

    resultados_f1 = pd.DataFrame({
        "Modelo": ["Decision Tree", "Logistic Regression", "Multilayer Perceptron"],
        "F1 Promedio": [f1_tree, f1_lr, f1_mlp]
    })

display(resultados_f1)

# ------------------------------------------------------------
# 2. Seleccionar el mejor clasificador ya entrenado
# ------------------------------------------------------------

with medir_rendimiento("Asignación clasificador final", detalle="Asignar mejor_clf según modelo con mayor F1", unidades=1, unidad_nombre="modelo seleccionado"):
    mejor_indice = resultados_f1["F1 Promedio"].idxmax()
    mejor_modelo_nombre = resultados_f1.loc[mejor_indice, "Modelo"]
    mejor_f1 = resultados_f1.loc[mejor_indice, "F1 Promedio"]

    if mejor_modelo_nombre == "Decision Tree":
        mejor_clf = tree_clf
    elif mejor_modelo_nombre == "Logistic Regression":
        mejor_clf = lr_clf
    else:
        mejor_clf = mlp_clf

print("Mejor modelo seleccionado:", mejor_modelo_nombre)
print("F1 promedio:", round(mejor_f1, 4))

# ------------------------------------------------------------
# 3. Guardar solo el clasificador en un archivo .joblib
# ------------------------------------------------------------

nombre_archivo = "predictor_suscripcion.joblib"

with medir_rendimiento("Guardado modelo Joblib", detalle=f"joblib.dump(mejor_clf, {nombre_archivo})", unidades=1, unidad_nombre="archivo"):
    joblib.dump(mejor_clf, nombre_archivo)

print("Modelo guardado correctamente en:", nombre_archivo)

# ------------------------------------------------------------
# 4. Descargar el archivo si estás usando Google Colab
# ------------------------------------------------------------

try:
    from google.colab import files
    files.download(nombre_archivo)
except:
    print("No se detectó Google Colab. El modelo quedó guardado en la carpeta del notebook.")

# ============================================================
# CARGAR MODELO Y SIMULAR PREDICCIÓN CON VALORES FICTICIOS
# ============================================================

import pandas as pd
import joblib

# ------------------------------------------------------------
# 1. Cargar el clasificador guardado
# ------------------------------------------------------------

with medir_rendimiento("Carga modelo Joblib", detalle=f"joblib.load({nombre_archivo})", unidades=1, unidad_nombre="archivo"):
    modelo_cargado = joblib.load(nombre_archivo)

print("Modelo cargado correctamente.")

# ------------------------------------------------------------
# 2. Crear un registro ficticio con las mismas variables usadas
#    para entrenar el modelo
# ------------------------------------------------------------

with medir_rendimiento("Creación registro ficticio", detalle="pd.DataFrame con una observación de ejemplo", unidades=1, unidad_nombre="registro"):
    registro_ficticio = pd.DataFrame([{
        "age": 56,
        "job": 0,
        "marital": 1,
        "education": 1,
        "default": 0,
        "balance": 45,
        "housing": 0,
        "loan": 0,
        "contact": 2,
        "day": 5,
        "month": 8,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": 3,
        "es_cliente_nuevo": 1,
        "tiene_doble_prestamo": 0,
        "duration_min": 24.45,
        "id": 2
    }])

print("Registro ficticio ingresado:")
display(registro_ficticio)

# ------------------------------------------------------------
# 3. Escalar el registro ficticio (¡Corregido de verdad!)
# ------------------------------------------------------------

# Creamos una copia sin la columna 'id' para que coincida con el fit
registro_para_escalar = registro_ficticio.drop(columns=['id'])

with medir_rendimiento("Escalamiento registro inferencia", detalle="escalar.transform(registro_ficticio)", unidades=len(registro_para_escalar), unidad_nombre="registro"):
    # AHORA SÍ: Usamos directamente tu objeto escalar de scikit-learn
    registro_ficticio_escalado = escalar.transform(registro_para_escalar)

# ------------------------------------------------------------
# 4. Realizar predicción de clasificación
# ------------------------------------------------------------

with medir_rendimiento("Inferencia registro ficticio", detalle="modelo_cargado.predict(registro_ficticio_escalado)", unidades=len(registro_ficticio_escalado), unidad_nombre="registro"):
    prediccion = modelo_cargado.predict(registro_ficticio_escalado)

print("Clasificación predicha suscripción depósito:", prediccion[0])

# ------------------------------------------------------------
# 5. Obtener probabilidades por clase
# ------------------------------------------------------------

with medir_rendimiento("Probabilidades inferencia", detalle="modelo_cargado.predict_proba(registro_ficticio_escalado)", unidades=len(registro_ficticio), unidad_nombre="registro"):
    probabilidades = modelo_cargado.predict_proba(registro_ficticio_escalado)

df_probabilidades = pd.DataFrame({
    "Clase depósito": modelo_cargado.classes_,
    "Probabilidad": probabilidades[0]
})

print("Probabilidades de clasificación:")
display(df_probabilidades)

# Resumen de rendimiento del pipeline
# ============================================================
# TABLAS FINALES DE RENDIMIENTO
# ============================================================

import pandas as pd
import numpy as np
from IPython.display import display, Markdown

df_rendimiento_detalle = pd.DataFrame(registros_rendimiento)

if df_rendimiento_detalle.empty:
    print("No existen mediciones registradas. Ejecuta el notebook desde el inicio para generar el resumen.")
else:
    # Identificar cuellos de botella principales
    idx_tiempo = df_rendimiento_detalle["Tiempo ejecución (s)"].idxmax()
    idx_ram = df_rendimiento_detalle["RAM pico aprox. (MB)"].idxmax()

    def _texto_tiempo(s):
        return f"{s:.3f} s"

    def _texto_cpu(cpu):
        if pd.isna(cpu):
            return "No disponible"
        return f"{cpu:.1f}% aprox."

    def _texto_ram(row):
        if pd.isna(row["RAM pico aprox. (MB)"]):
            return "No disponible"
        delta = row["RAM delta (MB)"]
        delta_txt = "No disponible" if pd.isna(delta) else f"{delta:+.2f} MB"
        return f"Pico {row['RAM pico aprox. (MB)']:.2f} MB / Δ {delta_txt}"

    def _texto_latencia(row):
        lat = row["Latencia aprox. (ms/unidad)"]
        unidades = row["Unidades procesadas"]
        unidad = row["Unidad"]
        if pd.isna(lat):
            return "No aplica"
        return f"{lat:.4f} ms/{unidad} ({unidades} {unidad})"

    def _texto_estabilidad(row):
        if "Estabilidad CV" in row.index and pd.notna(row.get("Estabilidad CV", np.nan)):
            return row["Estabilidad CV"]
        return "OK: sin errores registrados" if row["Estado"] == "OK" else "ERROR: revisar log"

    def _texto_cuello(row):
        marcas = []
        if row.name == idx_tiempo:
            marcas.append("Mayor tiempo")
        if row.name == idx_ram:
            marcas.append("Mayor RAM pico")
        return ", ".join(marcas) if marcas else "No principal"

    df_resumen_rendimiento = pd.DataFrame({
        "Punto clave": df_rendimiento_detalle["Operación"],
        "Tiempo de ejecución": df_rendimiento_detalle["Tiempo ejecución (s)"].apply(_texto_tiempo),
        "Consumo de CPU": df_rendimiento_detalle["CPU proceso aprox. (%)"].apply(_texto_cpu),
        "Consumo de memoria (RAM)": df_rendimiento_detalle.apply(_texto_ram, axis=1),
        "Latencia": df_rendimiento_detalle.apply(_texto_latencia, axis=1),
        "Estabilidad": df_rendimiento_detalle.apply(_texto_estabilidad, axis=1),
        "Cuello de botella": df_rendimiento_detalle.apply(_texto_cuello, axis=1),
        "Logs": df_rendimiento_detalle["Log"]
    })

    display(Markdown("### Tabla resumen por punto clave del pipeline"))

    try:
        display(
            df_resumen_rendimiento.style
            .hide(axis="index")
            .set_table_styles([
                {"selector": "th", "props": [("background-color", "#156082"), ("color", "white"), ("font-weight", "bold"), ("text-align", "center")]},
                {"selector": "td", "props": [("border", "1px solid white"), ("padding", "6px"), ("vertical-align", "top")]},
            ])
        )
    except Exception:
        display(df_resumen_rendimiento)

    # Tabla final tipo resumen conceptual, alineada a la tabla de referencia del usuario
    tiempo_total = df_rendimiento_detalle["Tiempo ejecución (s)"].sum()
    cpu_prom = df_rendimiento_detalle["CPU proceso aprox. (%)"].replace([np.inf, -np.inf], np.nan).mean()
    ram_pico = df_rendimiento_detalle["RAM pico aprox. (MB)"].max()
    errores = df_rendimiento_detalle[df_rendimiento_detalle["Estado"] != "OK"]
    cuello_tiempo = df_rendimiento_detalle.loc[idx_tiempo, "Operación"]
    cuello_ram = df_rendimiento_detalle.loc[idx_ram, "Operación"]

    latencias_validas = df_rendimiento_detalle["Latencia aprox. (ms/unidad)"].replace([np.inf, -np.inf], np.nan).dropna()
    latencia_prom = latencias_validas.mean() if not latencias_validas.empty else np.nan

    df_resumen_conceptos = pd.DataFrame([
        {
            "Concepto": "Tiempo de ejecución",
            "Resultado medido en este notebook": f"Tiempo total instrumentado: {tiempo_total:.3f} s. Operación más lenta: {cuello_tiempo}."
        },
        {
            "Concepto": "Consumo de CPU",
            "Resultado medido en este notebook": "No disponible" if pd.isna(cpu_prom) else f"CPU promedio aproximada del proceso: {cpu_prom:.1f}%."
        },
        {
            "Concepto": "Consumo de memoria (RAM)",
            "Resultado medido en este notebook": "No disponible" if pd.isna(ram_pico) else f"RAM pico aproximada observada: {ram_pico:.2f} MB. Mayor RAM pico: {cuello_ram}."
        },
        {
            "Concepto": "Latencia",
            "Resultado medido en este notebook": "No aplica" if pd.isna(latencia_prom) else f"Latencia promedio aproximada de las operaciones con unidades definidas: {latencia_prom:.4f} ms/unidad."
        },
        {
            "Concepto": "Estabilidad",
            "Resultado medido en este notebook": "Sin errores registrados en los bloques instrumentados." if errores.empty else f"Se registraron {len(errores)} bloque(s) con error. Revisar columna Logs."
        },
        {
            "Concepto": "Cuello de botella",
            "Resultado medido en este notebook": f"Principal por tiempo: {cuello_tiempo}. Principal por RAM pico: {cuello_ram}."
        },
        {
            "Concepto": "Logs",
            "Resultado medido en este notebook": "Todos los bloques finalizaron OK." if errores.empty else "Existen errores registrados; revisar tabla detallada."
        },
    ])

    display(Markdown("### Tabla resumen conceptual"))

    try:
        display(
            df_resumen_conceptos.style
            .hide(axis="index")
            .set_table_styles([
                {"selector": "th", "props": [("background-color", "#156082"), ("color", "white"), ("font-weight", "bold"), ("text-align", "center")]},
                {"selector": "td", "props": [("border", "1px solid white"), ("padding", "6px"), ("vertical-align", "top")]},
            ])
        )
    except Exception:
        display(df_resumen_conceptos)

    display(Markdown("### Detalle técnico crudo"))

    columnas_detalle = [
        "Fecha/hora",
        "Operación",
        "Detalle",
        "Tiempo ejecución (s)",
        "CPU proceso aprox. (%)",
        "CPU proceso (s)",
        "RAM inicial (MB)",
        "RAM final (MB)",
        "RAM pico aprox. (MB)",
        "RAM delta (MB)",
        "Unidades procesadas",
        "Unidad",
        "Latencia aprox. (ms/unidad)",
        "Estado",
        "Log"
    ]

    columnas_existentes = [c for c in columnas_detalle if c in df_rendimiento_detalle.columns]
    display(df_rendimiento_detalle[columnas_existentes])

import joblib
import pandas as pd


archivo_datos = "datos_02_bank_validados.csv"
print(f"Cargando dataset original desde: {archivo_datos}")
df_completo = pd.read_csv(archivo_datos)

archivo_modelo = "predictor_suscripcion.joblib"
print(f"Cargando red neuronal desde: {archivo_modelo}")
modelo_mlp = joblib.load(archivo_modelo)

print(" Sincronizando dimensiones y calculando predicciones...")

try:
    df_banco = df_completo.loc[X_test.index].copy()
except AttributeError:
    tamanio_test = len(X_test)
    df_banco = df_completo.tail(tamanio_test).copy()


df_banco["Predicion_Target"] = modelo_mlp.predict(X_test)

df_banco["Probabilidad_Exito"] = modelo_mlp.predict_proba(X_test)[:, 1]


archivo_salida = "predicciones_bank_marketing.csv"
df_banco.to_csv(archivo_salida, index=False)

print(f"\n Archivo '{archivo_salida}' generado con {len(df_banco)} registros.")
print("Ya puedes descargarlo desde tu panel izquierdo para cargarlo directamente en Power BI.")