# -*- coding: utf-8 -*-
"""Validación de datos - Caso 2 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQ1LAQZZli-3087je2hIbTRWRfI95tit
"""

# Validación, limpieza y generación de logs para el Dataset del Caso de estudio N°2
# Dataset: datos_02_bank_preprocesados.csv

# CELDA 1 Librerías #
from pathlib import Path
from datetime import datetime
import shutil
import numpy as np
import pandas as pd

# CELDA 2 #  Definir parámetros
PROJECT_ROOT = Path.cwd()

# Carpetas
RAW_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
REPORTS_DIR = PROJECT_ROOT / "reports"

# Archivos
INPUT_FILENAME = "datos_02_bank_preprocesados.csv"
OUTPUT_FILENAME = "datos_02_bank_validados.csv"
LOG_FILENAME = "reporte_errores_bank.csv"

# RUTAS COMPLETAS (Asegúrate de ejecutar esta parte)
INPUT_FILE = RAW_DIR / INPUT_FILENAME
OUTPUT_FILE = PROCESSED_DIR / OUTPUT_FILENAME
LOG_FILE = REPORTS_DIR / LOG_FILENAME
README_FILE = PROJECT_ROOT / "README.md"  # <--- ESTA ES LA LÍNEA QUE FALTABA

# CELDA 3 Archivos existentes#

def preparar_carpetas() -> None:
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

preparar_carpetas()
print(f"Estructura de carpetas lista en: {PROJECT_ROOT}")

# CELDA 4 Trazabilidad#

def registrar_log(logs: list, nivel: str, etapa: str, columna: str,
                  descripcion: str, filas_afectadas: int, accion: str) -> None:
    logs.append({
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "nivel": nivel,
        "etapa": etapa,
        "columna": columna,
        "descripcion": descripcion,
        "filas_afectadas": int(filas_afectadas),
        "accion": accion
    })

# CELDA 5 Sincronización de log y manejo de errores#

def cargar_dataset(logs: list) -> pd.DataFrame:
    archivo_en_carpeta_actual = PROJECT_ROOT / INPUT_FILENAME

    if not INPUT_FILE.exists() and archivo_en_carpeta_actual.exists():
        shutil.copy(archivo_en_carpeta_actual, INPUT_FILE)
        registrar_log(logs, "INFO", "Carga", "TODAS", "Archivo copiado a data/raw/", 0, "Copy")

    if not INPUT_FILE.exists():
        raise FileNotFoundError(f"No se encontró {INPUT_FILENAME}. Ubícalo en data/raw/")

    # Cambiado a read_csv para tu archivo .csv
    df = pd.read_csv(INPUT_FILE)

    registrar_log(logs, "INFO", "Carga", "TODAS", "Dataset cargado", len(df), "Lectura CSV")
    return df

# CELDA 6 Limpieza, normalización#

def estandarizar_nombres_columnas(df: pd.DataFrame, logs: list) -> pd.DataFrame:
    """
    Estandariza los nombres de las columnas del dataset.
    """
    df = df.copy()
    columnas_originales = df.columns.tolist()

    df.columns = (
        df.columns
        .astype(str)
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
        .str.replace("-", "_", regex=False)
        .str.replace(".", "", regex=False)
    )

    columnas_nuevas = df.columns.tolist()

    registrar_log(
        logs=logs,
        nivel="INFO",
        etapa="Estandarización de columnas",
        columna="TODAS",
        descripcion=f"Columnas estandarizadas. Antes: {columnas_originales}. Después: {columnas_nuevas}.",
        filas_afectadas=0,
        accion="Normalización de nombres de columnas"
    )

    return df

# CELDA 7 Reglas de negocio#

def validar_semantica_bank(df: pd.DataFrame, logs: list) -> pd.DataFrame:
    # Regla: Duración no puede ser negativa
    duracion_negativa = df[df['duration'] < 0]
    if not duracion_negativa.empty:
        registrar_log(logs, "ERROR", "Semántica", "duration", "Duraciones negativas encontradas", len(duracion_negativa), "Revisar origen")

    # Regla: Si pdays es -1, previous debe ser 0
    inconsistencia_previos = df[(df['pdays'] == -1) & (df['previous'] != 0)]
    if not inconsistencia_previos.empty:
        registrar_log(logs, "WARNING", "Semántica", "pdays/previous", "Inconsistencia en historial previo", len(inconsistencia_previos), "Notificar")

    # Regla: Edad mínima 18 años
    menores_edad = df[df['age'] < 18]
    if not menores_edad.empty:
        registrar_log(logs, "ERROR", "Semántica", "age", "Clientes menores de 18 años", len(menores_edad), "Filtrar o revisar")

    return df

# CELDA 8 Granularidad y flujo#
def eliminar_filas_vacias(df: pd.DataFrame, logs: list) -> pd.DataFrame:
    df = df.copy()
    filas_antes = len(df)
    df = df.dropna(how="all")
    filas_eliminadas = filas_antes - len(df)
    if filas_eliminadas > 0:
        registrar_log(logs, "WARNING", "Limpieza básica", "TODAS", "Filas vacías eliminadas", filas_eliminadas, "dropna")
    return df

def eliminar_duplicados(df: pd.DataFrame, logs: list) -> pd.DataFrame:
    df = df.copy()
    filas_antes = len(df)
    df = df.drop_duplicates()
    filas_eliminadas = filas_antes - len(df)
    if filas_eliminadas > 0:
        registrar_log(logs, "WARNING", "Limpieza básica", "TODAS", "Registros duplicados eliminados", filas_eliminadas, "drop_duplicates")
    return df

def eliminar_registros_con_nulos(df: pd.DataFrame, logs: list) -> pd.DataFrame:
    df = df.copy()
    filas_con_nulos = df.isna().any(axis=1)
    cantidad_nulos = filas_con_nulos.sum()
    df = df.loc[~filas_con_nulos].copy()
    if cantidad_nulos > 0:
        registrar_log(logs, "WARNING", "Limpieza básica", "TODAS", "Filas con nulos eliminadas", cantidad_nulos, "Eliminar nulos")
    return df

def limpieza_basica(df: pd.DataFrame, logs: list) -> pd.DataFrame:
    """
    Esta es la función que te falta en memoria.
    Ejecuta esta celda para definirla.
    """
    df = eliminar_filas_vacias(df, logs)
    df = eliminar_duplicados(df, logs)
    df = eliminar_registros_con_nulos(df, logs)
    return df

# Visualización limpieza (Prueba)
logs = []

df_raw = cargar_dataset(logs)

try:
  #  Estructura
  df = cargar_dataset(logs)
  df = estandarizar_nombres_columnas(df, logs)
  df = limpieza_basica(df, logs)
  # Reglas de negocio
  df = validar_semantica_bank(df, logs)
  df = validar_rangos(df, logs)

  df = crear_columnas_derivadas(df, logs)

  guardar_resultados(df, logs)
  actualizar_readme(df_raw, df, logs)
  print(f"Dataset final listo para análisis con {len(df)} filas.")

except Exception as e:
    print(f'error {e}')

# CELDA 9 Integración, guardado de reportes#

# Inicializar logs
logs_proceso = []

try:
    # 1. Cargar
    df_bank = cargar_dataset(logs_proceso)

    # 2. Estandarizar
    df_bank = estandarizar_nombres_columnas(df_bank, logs_proceso)
    df_namk = limpieza_basica(df_bank, logs_proceso)

    # 3. Validar Semántica
    df_bank = validar_semantica_bank(df_bank, logs_proceso)

    # 4. Guardar resultados
    df_bank.to_csv(OUTPUT_FILE, index=False)

    # 5. Guardar reporte de errores
    pd.DataFrame(logs_proceso).to_csv(LOG_FILE, index=False)

    print(f"Proceso finalizado. Reporte generado en: {LOG_FILE}")

except Exception as e:
    print(f"Error en el pipeline: {e}")

# CELDA 10 Validar calidad de datos, Reglas de negocio#

import numpy as np

def obtener_reglas_rango() -> dict:
    return {
        "age": (18, 100),
        "day": (1, 31),
        "campaign": (1, 50),
        "previous": (0, 300),
        "pdays": (-1, 999),
        "duration": (0, 5000),
        "balance": (-10000, 500000)
    }

def validar_rangos(df: pd.DataFrame, logs: list) -> pd.DataFrame:
    df = df.copy()
    reglas = obtener_reglas_rango()
    columnas_numericas = df.select_dtypes(include=[np.number]).columns.tolist()

    for col in columnas_numericas:
        valores_unicos = set(df[col].dropna().unique().tolist())
        if len(valores_unicos) > 0 and valores_unicos.issubset({0, 1}):
            reglas[col] = (0, 1)

    for col, (valor_min, valor_max) in reglas.items():
        if col not in df.columns: continue
        condicion_valida = df[col].between(valor_min, valor_max, inclusive="both")
        fuera_de_rango = (~condicion_valida).sum()
        if fuera_de_rango > 0:
            df = df.loc[condicion_valida].copy()
            registrar_log(logs, "ERROR", "Validación de rangos", col,
                          f"Valores fuera de [{valor_min}, {valor_max}]",
                          fuera_de_rango, "Eliminación de registros")
    return df

# CELDA 11 Guardado #
def guardar_resultados(df: pd.DataFrame, logs: list) -> None:
    """
    Guarda el dataset validado y el reporte de errores en las carpetas correspondientes.
    """
    # Guardamos el dataset limpio en formato CSV
    df.to_csv(OUTPUT_FILE, index=False, encoding="utf-8")

    # Guardamos los logs de validación
    df_logs = pd.DataFrame(logs)
    df_logs.to_csv(LOG_FILE, index=False, encoding="utf-8-sig")

    print("--- PROCESO DE GUARDADO EXITOSO ---")
    print(f"1. Dataset validado: {OUTPUT_FILE}")
    print(f"2. Reporte de errores: {LOG_FILE}")

# CELDA 12 #

def crear_columnas_derivadas(df: pd.DataFrame, logs: list) -> pd.DataFrame:
    df = df.copy()
    columnas_creadas = []

    # 1. Identificar si es un cliente nuevo (nunca contactado antes)
    if "pdays" in df.columns:
        df["es_cliente_nuevo"] = (df["pdays"] == -1).astype(int)
        columnas_creadas.append("es_cliente_nuevo")

    # 2. Score de endeudamiento (si tiene hipoteca Y préstamo personal)
    if "housing" in df.columns and "loan" in df.columns:
        df["tiene_doble_prestamo"] = ((df["housing"] == 1) & (df["loan"] == 1)).astype(int)
        columnas_creadas.append("tiene_doble_prestamo")

    # 3. Duración en minutos (más fácil de interpretar que segundos)
    if "duration" in df.columns:
        df["duration_min"] = df["duration"] / 60
        columnas_creadas.append("duration_min")

    df["fecha_procesamiento"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    columnas_creadas.append("fecha_procesamiento")

    registrar_log(logs, "INFO", "Columnas derivadas", "TODAS",
                  f"Creadas: {columnas_creadas}", len(df), "Feature Engineering")
    return df

# CELDA 13 auto-doc #
def actualizar_readme(df_original: pd.DataFrame, df_limpio: pd.DataFrame, logs: list) -> None:
    fecha = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    filas_eliminadas = len(df_original) - len(df_limpio)

    # Calcular problemas detectados desde los logs
    resumen_logs = pd.DataFrame(logs)
    problemas_detectados = 0
    if not resumen_logs.empty:
        problemas_detectados = resumen_logs[resumen_logs["nivel"].isin(["WARNING", "ERROR"])]["filas_afectadas"].sum() if "filas_afectadas" in resumen_logs.columns else 0

    seccion = f'''
## Validación y Limpieza: Caso Bank Marketing
**Fecha de ejecución:** {fecha}

### Resumen del Procesamiento
- **Filas originales:** {len(df_original)}
- **Filas finales:** {len(df_limpio)}
- **Filas eliminadas:** {filas_eliminadas}

### Archivos
- Dataset validado: `{OUTPUT_FILE.name}`
- Reporte: `{LOG_FILE.name}`
'''
    # Uso de la variable global README_FILE
    if README_FILE.exists():
        contenido_actual = README_FILE.read_text(encoding="utf-8")
    else:
        contenido_actual = "# Proyecto Bank Marketing\n"

    README_FILE.write_text(contenido_actual + seccion, encoding="utf-8")
    print(f"README actualizado en: {README_FILE}")

# CELDA 14 #

def actualizar_readme(df_original: pd.DataFrame, df_limpio: pd.DataFrame, logs: list) -> None:
    fecha = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    filas_eliminadas = len(df_original) - len(df_limpio)

    seccion = f'''
## Validación y Limpieza: Caso Bank Marketing
**Fecha de ejecución:** {fecha}

### Resumen del Negocio
- **Objetivo:** Optimizar ROI de depósitos a plazo.
- **Filas iniciales:** {len(df_original)}
- **Filas tras limpieza:** {len(df_limpio)}
- **Registros eliminados:** {filas_eliminadas} (duplicados, nulos o fuera de rango).

### Reglas de Calidad Aplicadas
1. **Filtro de Edad:** Solo clientes entre 18 y 100 años.
2. **Consistencia de Campaña:** Se eliminaron llamadas con duración negativa.
3. **Normalización:** Los campos de texto se estandarizaron a MAYÚSCULAS.
4. **Ingeniería de Datos:** Se creó la variable `es_cliente_nuevo` para diferenciar estrategias de marketing.
'''
    # (Resto del código de escritura del archivo igual al original)
    if README_FILE.exists():
        contenido_actual = README_FILE.read_text(encoding="utf-8")
    else:
        contenido_actual = "# Pipeline de Datos Bancarios\n"
    README_FILE.write_text(contenido_actual + seccion, encoding="utf-8")

# CELDA 15 Manejo de rutas, logs#
def actualizar_readme(df_original: pd.DataFrame, df_limpio: pd.DataFrame, logs: list) -> None:
    """
    Actualiza el archivo README.md con el resumen del Caso de Marketing Bancario.
    """
    fecha = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    filas_eliminadas = len(df_original) - len(df_limpio)

    resumen_logs = pd.DataFrame(logs)
    problemas_detectados = 0
    if not resumen_logs.empty:
        # Sumamos las filas afectadas por errores o advertencias
        problemas_detectados = resumen_logs[
            resumen_logs["nivel"].isin(["WARNING", "ERROR"])
        ]["filas_afectadas"].sum()

    seccion = f'''

## Validación y limpieza: Caso Bank Marketing (Depósitos a Plazo)

**Fecha de ejecución:** {fecha}

### Archivos utilizados
- Dataset de entrada: `{INPUT_FILE.relative_to(PROJECT_ROOT)}`
- Dataset validado: `{OUTPUT_FILE.relative_to(PROJECT_ROOT)}`
- Reporte de errores: `{LOG_FILE.relative_to(PROJECT_ROOT)}`

### Resumen del procesamiento
- **Registros iniciales:** {len(df_original)}
- **Registros finales:** {len(df_limpio)}
- **Registros descartados:** {filas_eliminadas}
- **Inconsistencias detectadas:** {int(problemas_detectados)}

### Validaciones y Transformaciones Aplicadas
1. **Estandarización Estructural:**
   - Nombres de columnas convertidos a minúsculas y sin espacios (Snake Case).
   - Limpieza de espacios en blanco en datos categóricos.
2. **Limpieza de Calidad:**
   - Eliminación de registros duplicados y valores nulos.
3. **Validación Semántica de Negocio:**
   - **Edad:** Filtro de clientes fuera del rango 18-100 años.
   - **Duración:** Verificación de llamadas con tiempo válido (mayor a 0).
   - **Historial:** Consistencia lógica entre contactos previos (`previous`) y días transcurridos (`pdays`).
4. **Ingeniería de Variables (Derivadas):**
   - Creación de la variable `es_cliente_nuevo` (basada en pdays).
   - Cálculo de `duration_min` para facilitar la interpretación del ROI.

### Objetivo del Proceso
Asegurar que el modelo de Machine Learning sea entrenado con datos coherentes para identificar a los clientes con mayor probabilidad de suscribir un depósito, optimizando los recursos del banco.
'''

    # Escribir el archivo
    if README_FILE.exists():
        # Opcional: puedes sobrescribirlo totalmente para que no se acumule lo de postulaciones
        README_FILE.write_text("# Pipeline de Datos: Bank Marketing\n" + seccion, encoding="utf-8")
    else:
        README_FILE.write_text("# Pipeline de Datos: Bank Marketing\n" + seccion, encoding="utf-8")

    print(f"README corregido y actualizado en: {README_FILE}")

# CELDA 16 Monitoreo # Ejecución completa del pipeline adaptada al Caso Bank Marketing
logs = []

# 1. Cargar datos.
df_original = cargar_dataset(logs)

# 2. Estandarizar nombres y formatos.
# Asegúrate de haber ejecutado las celdas donde definimos estas funciones
df_procesado = estandarizar_nombres_columnas(df_original, logs)

# 3. Limpieza básica (Eliminar vacíos, duplicados y nulos)
df_procesado = limpieza_basica(df_procesado, logs)

# 4. Validación de rangos (Edad, Duración, Balances, etc.)
df_procesado = validar_rangos(df_procesado, logs)

# 5. Crear columnas derivadas (Variables de negocio nuevas)
df_procesado = crear_columnas_derivadas(df_procesado, logs)

# 6. Guardar resultados
guardar_resultados(df_procesado, logs)

# 7. Actualizar archivo README.md
actualizar_readme(df_original, df_procesado, logs)

print("\n--- RESUMEN DEL PROCESO BANCARIO ---")
print(f"- Registros cargados: {len(df_original)}")
print(f"- Registros tras limpieza: {len(df_procesado)}")
print(f"- Filas descartadas: {len(df_original) - len(df_procesado)}")
print(f"- Nuevas variables creadas: {len(df_procesado.columns) - len(df_original.columns)}")

# CELDA 17 #

# Revisión de Dataset limpio
df_procesado.head()

# CELDA 18 #
import pandas as pd

# Revisión de reporte de errores
df_logs = pd.DataFrame(logs)

if df_logs.empty:
    print(" No se registraron eventos de error en el log. Datos limpios")
else:
    print(" Reporte de incidencias encontradas:")
    display(df_logs)

# CELDA 19 Verificaciones de tipo#

# Validación de finales
print("--- RESUMEN DE CALIDAD FINAL ---")

print(f"- Filas duplicadas: {df_procesado.duplicated().sum()}")
print(f"- Valores nulos totales: {df_procesado.isna().sum().sum()}")
print(f"- Total de registros finales: {len(df_procesado)}")
print(f"- Total de variables (incluyendo derivadas): {len(df_procesado.columns)}")

# Validaciones específicas de Negocio Bancario
if "age" in df_procesado.columns:
    fuera_edad = ((df_procesado['age'] < 18) | (df_procesado['age'] > 100)).sum()
    print(f"- Clientes con edad fuera de rango (18-100): {fuera_edad}")

if "duration" in df_procesado.columns:
    duracion_anomala = (df_procesado['duration'] <= 0).sum()
    print(f"- Llamadas con duración cero o negativa: {duracion_anomala}")

if "balance" in df_procesado.columns:
    print(f"- Saldo promedio anual (mín/máx): {df_procesado['balance'].min()} / {df_procesado['balance'].max()}")

print("\n--- ESTRUCTURA TÉCNICA DE SALIDA ---")
display(df_procesado.dtypes.to_frame("tipo_dato"))

# CELDA 20 transformación dataset#
# Comprobaciones:
  # Cuantitativa
  # Comparación directa de DataFrames
print("--- COMPARATIVA DE RESULTADOS ---")
print(f"Dataset Original: {df_original.shape[0]} filas, {df_original.shape[1]} columnas")
print(f"Dataset Validado: {df_procesado.shape[0]} filas, {df_procesado.shape[1]} columnas")

filas_eliminadas = df_original.shape[0] - df_procesado.shape[0]
columnas_nuevas = df_procesado.shape[1] - df_original.shape[1]

print(f"\nResumen de cambios:")
print(f"- Se eliminaron {filas_eliminadas} filas (por nulos, duplicados o fuera de rango).")
print(f"- Se crearon {columnas_nuevas} columnas nuevas (derivadas/features).")

# CELDA 21 Transparencia, logs y warnings#
# Comparación de documentación (logs)
# Leer el reporte de errores generado
import pandas as pd
df_reporte = pd.read_csv(LOG_FILE)

# Ver solo los errores que causaron eliminación de datos
errores_criticos = df_reporte[df_reporte['nivel'].isin(['ERROR', 'WARNING'])]
display(errores_criticos)

# CELDA 22 Validación #
# Comprobar cambios en variables específicas
# Comparar rangos de edad
comparativo_age = pd.DataFrame({
    'Antes (Original)': [df_original['age'].min(), df_original['age'].max()],
    'Después (Validado)': [df_procesado['age'].min(), df_procesado['age'].max()]
}, index=['Edad Mínima', 'Edad Máxima'])

print("Cambios en rangos de Edad:")
display(comparativo_age)

# Verificar la creación de columnas derivadas
if 'es_cliente_nuevo' in df_procesado.columns:
    print("\n La validación aprobó la creación de 'es_cliente_nuevo'.")
    print(df_procesado['es_cliente_nuevo'].value_counts().to_frame("Cantidad"))